### ISSUE TITLE
Getting error post user tries to create company which doesn't exists in ClearBit on DEV Environment

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2451] opened 2021-01-14 15:09 UTC
Getting error post user tries to create company which doesn't exists in Clearbit on Staging environment. 
![image (7).png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/7ee9897f-e9b9-4efb-9d27-c5a11fc1e8d3)

**Comment by amolsontakke3576** [comment] 2021-01-14 15:53
The issue is from org-service and already logged a ticket for this 
https://jira.linuxfoundation.org/browse/PMM-1013

So closing this now.

**Closed by amolsontakke3576** 2021-01-14 15:53 UTC
Labels: Contributor Console for V2, tier-2, v2
