### ISSUE TITLE
Contributor is getting error message while contacting CLA Manager

### ISSUE THREAD

**Issue by kdhaigud** [communitybridge/easycla#551] opened 2020-02-04 14:40 UTC
## Summary

When contributor tries to send CCLA request to manger user is getting error message
## Background

1. Goto Github
2. Send PR to configure repo
3. Click on not signed CLA bot
4. Select Corporate
5. select Company from list
6. Click on contact CLA manger
7. Enter manger details and own email address and click on send

## Expected behavior

User should be able to send request CLA manger

## Screenshots

![Screenshot from 2020-02-04 19-00-07](https://user-images.githubusercontent.com/52558085/73754383-57a96680-478a-11ea-9a72-80c28cd6c248.png)
![Screenshot from 2020-02-04 11-58-27](https://user-images.githubusercontent.com/52558085/73754386-57a96680-478a-11ea-8622-dd08c712e3a7.png)

**Comment by dealako** [comment] 2020-02-04 17:15
I think this may be related to a caching problem - or session timeout issue.

**Comment by kdhaigud** [comment] 2020-02-05 12:37
David I have tried in incognito window so I think it should not be caching problem
Can you please refer following video and screenshot and let me know if I am doing anything wrong here

[Connect mansger.zip](https://github.com/communitybridge/easycla/files/4159475/Connect.mansger.zip)

![Screenshot from 2020-02-05 17-56-19](https://user-images.githubusercontent.com/52558085/73841939-a49c4400-4841-11ea-991c-e355914904e6.png)

**Comment by dealako** [comment] 2020-02-26 20:27
We have updated this logic in DEV. We need to confirm if this is resolved in DEV.

**Comment by dealako** [comment] 2020-04-09 00:15
@nirupamav can you confirm this is still an issue. Coordinate with @hnexokonkwo if not.

**Comment by nirupamav** [comment] 2020-04-09 06:09
@dealako 
Observed that no error is displayed, but no action is performed when **_Select a CLA Manager from a list of options_** is selected and contributors selects CLA Manager email and contributor's email and clicks SEND. This was working fine few days back
![image](https://user-images.githubusercontent.com/60865903/78862744-b377c080-7a55-11ea-8281-f2a5877c4bf5.png)

![image](https://user-images.githubusercontent.com/60865903/78862779-c25e7300-7a55-11ea-9a8d-f306c4c4d159.png)


However when **_Enter CLA Manager Directly_** is selected and details are entered manually it is working fine
![image](https://user-images.githubusercontent.com/60865903/78862915-0ea9b300-7a56-11ea-9265-7d728880e22e.png)

![image](https://user-images.githubusercontent.com/60865903/78863057-50d2f480-7a56-11ea-936a-d3dabb82a0ee.png)

**Comment by nirupamav** [comment] 2020-04-17 09:34
**Verified and observed that the issue is fixed**

**Closed** 2020-06-03 18:05 UTC
Labels: Console - Contrib, bug, size:Small, v1
