### ISSUE TITLE
V2/V1 - Corporate Console - Document is not attached in email notification sent when CCLA is signed by signatory

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1456] opened 2020-07-22 16:10 UTC
1. In V1/V2 sign CCLA document for a project from Corporate Console
2. Email notification is sent to signatory with the link to access the signed document
3. Observed that signed CCLA document is not accessible from the link in the email
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/79c8f2c8-bc90-4165-b31e-3bb0cb98bea1)

**Comment by dealako** [comment] 2020-08-06 04:17
@nirupamav is this email from Docusign?

**Comment by nirupamav** [comment] 2020-08-06 05:22
@dealako 
No it is the email sent from EasyCLA.
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4a04d3a8-a0eb-41a7-8301-74a574267a78)

When clicked on the link in the email I get below error
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/faf82e82-466b-4ff1-908d-d6e1025d0bbd)

**Comment by dealako** [comment] 2020-08-06 15:01
@nirupamav can you share the link in the screenshot -> api.dev.lfcla.com/v3.....

**Comment by dealako** [comment] 2020-08-12 00:24
@makkalot probably an easy one to review and diagnose if still a problem. Reach out to @nirupamav via Slack to ask for test scenario/link (IST time zone).

Currently, the EasyCLA system sends out emails when the contributor or CLA Signatory signs a PDF via the DocuSign flow.  This isn't super important, but embedded in this email (instead of attaching a signed PDF) we have a link.  This link is to our [golang /v3 API](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L559) - (note the `operationId` and `tags` attributes in the swagger spec which points to the signatures package) where the [handler will hopefully process the request](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/signatures/handlers.go#L76).  We use our helper function to generate a signed URL that can give temporary access to the resource (PDF) which builds a small HTML response to redirect the user to the download.

One of several things can go wrong:

1. PDF doesn't exist (if so, we have other issues)
2. Permissions issue with signed URL (hasn't been a problem in the past, but not tested super well)
3. ID's got mixed up (???) and is pointed to a missing/non-existent document

If possible, coordinate with @nirupamav to see what went wrong.  She can forward you an example email to test against our DEV environment.  To test locally when you have your AWS permissions, you can change the URL to point to localhost:8080 instead of api.dev.lfca.com:443.

**Comment by makkalot** [comment] 2020-08-19 10:26
@dealako looks like the issue was temporary, cause @nirupamav  tested again and the feature seems to be working. Wondering if it was some temporary permission issue ... Anyways seems not much we can do on this one atm, if happens again we can re-open the ticket.

**Comment by nirupamav** [comment] 2020-08-19 10:31
Verified in V1 and V2 and observed that issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2402c680-eff6-41c2-9997-3345ece730db)

**Comment by dealako** [comment] 2020-08-19 15:45
Closing issue for now. Unable to reproduce.

**Closed by dealako** 2020-08-19 15:45 UTC
Labels: Console - Corp, Corporate Console for V2, bug, v1, v2
