### ISSUE TITLE
EasyCLA Individual and Corporate Authorization page will not redirect- Gerrit Only

### ISSUE THREAD

**Issue by tonitoles** [communitybridge/easycla#3946] opened 2023-05-17 17:15 UTC
The URL of where the issue occurred: https://contributor.easycla.lfx.linuxfoundation.org/#/cla/gerrit/project/d837d131-5742-424e-a515-36738dc49369/individual?redirect=https:%2F%2Fgerrit.o-ran-sc.org

Error Message displayed in UI: You are being redirected to the login page.     
Page does not redirect to login page
Test Environment (dev or prod): prod

Browser(s): Chrome, Internet Explorer

OS: Windows 11

Steps to Reproduce
1. Begin at link   https://gerrit.o-ran-sc.org/r/settings#Agreements
2. sign in 
3. Go to settings
4. Select **Agreements**
5. Select **New Contributor Agreement**
6. Select any of the agreement types because they all give the same results
7. Select **Please review the agreement**
8. Select **Proceed to Individual Authorization**

Actual Result (of the steps above): A page appears with the message **You are being redirected to the login page.**

Expected Result (why you are opening this ticket - why is this a defect?): I expect to be redirected to the login page

**Comment by feelinspired** [comment] 2023-05-18 10:04
+1

**Comment by nickmango** [comment] 2023-05-18 14:58
This will need further investigation on the contributor console (frontend). I have assigned and shall troubleshoot this with @amolsontakke3576

**Comment by amolsontakke3576** [comment] 2023-05-19 11:56
[@Heather](https://linuxfoundation.slack.com/team/ULA3RH9HN)
 
[@Veerendra Singh Thakur](https://linuxfoundation.slack.com/team/U01GDNY8MBK)
 As per my finding issue is with Auth0, If you are not already logged in then it is working fine (or you can logout user from stucked screen UI and login it again) but if you a are already logged in then Auth0 failed to re-login it.
[@Luis Mori Guerra](https://linuxfoundation.slack.com/team/UKYV2270X)
 Can you please help on it ? as I can see Auth0 login part written by you

**Comment by luismoriguerra** [comment] 2023-05-19 20:31
sure , after assessing the issue , seems like the new Gerrit page would need to validate if the user is already logged-in and redirect the user automatically

**Comment by mlehotskylf** [comment] 2023-05-25 15:26
Waiting for Auth fixes which is tracked in [PCC-3008](https://jira.linuxfoundation.org/browse/PCC-3008).

**Comment by mlehotskylf** [comment] 2023-05-26 15:27
Testing in progress.

**Comment by mlehotskylf** [comment] 2024-02-02 07:57
@thakurveerendras please confirm this is fixed and tested.
CC: @nickmango

**Comment by mlehotskylf** [comment] 2024-02-05 20:19
@thakurveerendras please let us know if you have any update on testing for this ticket.

**Comment by mlehotskylf** [comment] 2024-02-05 20:38
@thakurveerendras is this blocked by #4226?

**Comment by nickmango** [comment] 2024-02-12 17:46
@thakurveerendras As confirmed with the production project JuanSebastian availed for testing... this is as well reproducible in prod and is not a regression issue
cc @mlehotskylf

**Comment by mlehotskylf** [comment] 2024-02-21 16:47
@amolsontakke3576 this seems to be UI issue, can you please take a look when you have a chance?

**Comment by mlehotskylf** [comment] 2024-03-01 14:36
This is fixed but we have concerns about "circular" user flow where user is allowed to sign already signed CLA. This is not impacting the signing itself, but it is "not ideal" user experience.

**Comment by mlehotskylf** [comment] 2024-03-04 16:57
This is fixed as reported and "circular" user flow is by the design. Moving to QA.

**Comment by mlehotskylf** [comment] 2024-04-26 09:49
This is done so closing.

**Closed by mlehotskylf** 2024-04-26 09:49 UTC
Labels: bug, 01 - High, Gerrit
