### ISSUE TITLE
Add CLA Manager on project EasyCLA page

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#937] opened 2020-04-19 22:46 UTC
## Summary
Any user associated with a company will be taken to this page after they switch to member console, select project from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/Dfbd923b389bffae1192a3a2ca50c3faa)for the project page for EasyCLA.

![image](https://user-images.githubusercontent.com/57362064/79701658-6ae5b180-8264-11ea-9bce-1f8ebcaa61fd.png)

Step 3.1 in PRD 
https://confluence.linuxfoundation.org/display/PROD/Project+Dashboard+for+EasyCLA

User enters the First Name, Last Name and Email Address of the person whom user wants to add as a CLA Manager

All the backend operations will be encapsulated in EasyCLA API call. See PRD for more details.

## Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1 bug(s)

**Comment by nirupamav** [comment] 2020-05-14 11:12
@wanyaland 
Tried below scenarios and always 403/401 is displayed
Could you please let me know what values(sfid's or id's from CLA DB) needs to be provided for projectid and companyid. Also could you please share the acs details for the endpoints
|SL.No|Test Data|Response|
|----------|----------|-----------|
|1|Tried using sfid's for project and company <br>1. User(nirupamav) has project-manager role and has access to the project a0941000002wBz4AAE <br>2. User has lf-operations role <br>3. Company from 0014100000Te1DWAAZ has signed for CLA group Cello_CNCF in a0941000002wBz4AAE <br>https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a0941000002wBz4AAE/cla-manager|401 <br>unauthenticated for invalid credentials|
|2|Tried using id's from CLA DB for project and company <br>1. User(nirupamav) has project-manager role and has access to the project 67e9b2e1-44fc-4b67-9712-6610e80f507a <br>2. User has lf-operations role <br>3. Company from 4d9c760b-f5b3-4fe6-89b8-f7d9bd4d965c has signed for CLA group Cello_CNCF in 67e9b2e1-44fc-4b67-9712-6610e80f507a <br>https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/4d9c760b-f5b3-4fe6-89b8-f7d9bd4d965c/project/67e9b2e1-44fc-4b67-9712-6610e80f507a/cla-manager|401 <br>unauthenticated for invalid credentials|
|3|Tried using sfid's for project and company <br>1. User(clamanager) has user role <br>2. User has created company 0014100000Te1DWAAZ and signed CLA for project  a0941000002wBz4AAE <br>https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a0941000002wBz4AAE/cla-manager|403|
|4|Tried using id's from CLA DB for project and company <br>1. User(clamanager) has user role <br>2. User has created company 4d9c760b-f5b3-4fe6-89b8-f7d9bd4d965c  and signed CLA for project  67e9b2e1-44fc-4b67-9712-6610e80f507a <br>https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/4d9c760b-f5b3-4fe6-89b8-f7d9bd4d965c/project/67e9b2e1-44fc-4b67-9712-6610e80f507a/cla-manager|403|

**Comment by nirupamav** [comment] 2020-05-27 05:19
**_Tested and observed below issues_**
**Add CLA Manager Issues**
1. **Able to Add CLA Manager with firstName and lastName having only spaces**
![image](https://user-images.githubusercontent.com/60865903/82975382-ea039d80-9ff9-11ea-9be4-1b980d1275d3.png)
2. **Appropriate error message is not returned when trying to add duplicate CLA Manager record or when trying to add CLA Manager with same emailid and different firstName and lastName**
![image](https://user-images.githubusercontent.com/60865903/82975471-2931ee80-9ffa-11ea-8067-4fb2c6cb6edb.png)
3. **name is not returned in response after adding CLA Manager. Is name=firstName+lastName? if not are are we storing the firstName and lastName and using these values instead of the firstName and lastName from user service**
![image](https://user-images.githubusercontent.com/60865903/82975548-67c7a900-9ffa-11ea-8f76-980368b4694c.png)
4. **As per PRD when user does not exist, backend will send email to user to created lfid, but endpoint returns 400 saying user does not exist. Also email is not sent to user, asking the user to create lfid. Should this be handled at API level or is it handled from frontend**
![image](https://user-images.githubusercontent.com/60865903/82975841-2e436d80-9ffb-11ea-93f3-21393028fb5e.png)
5. **Appropriate error message is not returned when firstName and lastName fields are missing in the payload**
![image](https://user-images.githubusercontent.com/60865903/82976112-dd804480-9ffb-11ea-9343-bd4cac873afa.png)
6. **Appropriate error message is not returned when data is not provided for firstName and lastName fields**
![image](https://user-images.githubusercontent.com/60865903/82976299-52537e80-9ffc-11ea-9b9c-123a59e09d28.png)
7. **500 internal server is returned when trying to add CLA Manager for a different projectsfid and clagroupd combination. clagroupid provided belongs other projectsfid**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a0941000002wBz4AAE/claGroup/3564e0ad-5da9-4164-a158-1234a9845f75/cla-manager
8. **500 internal server is returned when trying to add CLA Manager for CLA group of projectsfid for which there is no CCLA**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a0941000002wBz4AAE/claGroup/f8022c61-7782-4954-a50f-c957b457cd30/cla-manager
9. 500 internal server error is returned when trying to add CLA Manager with invalid cla group id
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a0941000002wBz4AAE/claGroup/f8022c61-7782-4954-a50f-c957b4/cla-manager

**Delete CLA Manager Issues**
Delete CLA Manager is not working. 403 is returned for CLA Manager role with appropriate roles scope.
Observed below issues in ACS policies. Not sure if 403 is returned due to this issue
**_Path in ACS policies_**
/v4/company/*/project/*/claGroup/*/cla-manager/*
**_Path in API docs_**
companySF/{companySFID}/projectSF/{projectSFID}/claGroup/{projectID}/cla-manager/{userLFID}
![image](https://user-images.githubusercontent.com/60865903/82980640-95671f00-a007-11ea-9cc9-a72846e8d029.png)

**Comment by nirupamav** [comment] 2020-05-28 15:33
@wanyaland 
I am still able to reproduce the issues that I reported above. Delete is also not working at all.

**Comment by nirupamav** [comment] 2020-05-29 06:29
Delete is working now but other issues still exist. I have updated few other issues in the above issue list.

**Comment by nirupamav** [comment] 2020-06-05 11:50
**_Tested and observed below issues_**
1. **Observed that for few users even if user exists in user service and as well as cla_dev_users, still 400 is returned and email to create user lfid is sent**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a092M00001IV4PgQAL/claGroup/3564e0ad-5da9-4164-a158-1234a9845f75/cla-manager?
![image](https://user-images.githubusercontent.com/60865903/83869545-5db84f80-a74a-11ea-98c3-fbe6fdf7ca75.png)

![image](https://user-images.githubusercontent.com/60865903/83869571-690b7b00-a74a-11ea-9177-4e0564507b37.png)

![image](https://user-images.githubusercontent.com/60865903/83869608-758fd380-a74a-11ea-8040-a19cb1d91469.png)

2. **Appropriate error message is not returned when trying to add duplicate CLA Manager record or when trying to add CLA Manager with same emailid and different firstName and lastName**
![image](https://user-images.githubusercontent.com/60865903/83870709-52feba00-a74c-11ea-9e14-0ecebbd06520.png)

3. **When firstname and lastname is different from user service, then 400 is returned with message as user not found, and email is sent to create lfid, eventhough user already exists with that emailid**
![image](https://user-images.githubusercontent.com/60865903/83871143-28613100-a74d-11ea-8b3b-6616122527ee.png)

![image](https://user-images.githubusercontent.com/60865903/83871167-33b45c80-a74d-11ea-9a19-71df147189ac.png)

![image](https://user-images.githubusercontent.com/60865903/83871265-66f6eb80-a74d-11ea-9c35-9b37cb5e48b3.png)

4. **When space is given at the end of the fields 400 below error message is displayed. Not sure if sapce trim has to be handled at API level or UI level. Adding the issue here for tracking purpose**
![image](https://user-images.githubusercontent.com/60865903/83872176-184a5100-a74f-11ea-93d6-70edd44f0abe.png)

**Comment by nirupamav** [comment] 2020-06-15 11:14
Closed by mistake reopening the ticket

**Comment by nirupamav** [comment] 2020-07-13 06:01
**_Retested and observed below issues_**
**1. Able to add a user who is not associated with any company (just user role) as CLA Manager to the project**
**User with onlu user role**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fa3b25b1-c0f1-464a-9dcd-152e2d179ffb)

**Add CLA Manager post successful from API**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5cff8684-5705-4efa-82b9-b3f73e355081)

**User with only user role is assigned with CLA Manager role for the project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/77b71445-17c3-4b6c-a9b9-fb24ed1615eb)

**2. Observed that name provided in the API is not fetched in the API. Not sure about the significance of firstname and lastname provided in the API payload**
**Example1**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1ed33f3b-2299-4725-8375-c48ea6fb4f62)

**Example2**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6124c87d-f816-49d4-8618-29175546d179)

**3. The link to create LFID is still pointing to https://identity.linuxfoundation.org/ instead of myprofile link. Issue is tracked in Bug #1304** 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/487c318d-b462-4729-95d8-71662c9bd7aa)

**4. Email of the CLA Manager is not displayed in the email sent o create LFID**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cb7cd674-c9b8-4b3d-a4a5-7321f1a77485)

**5. Only one CLA Manager info is displayed in the email sent to create LFID even if there are multiple CLA Managers**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2564fa86-c466-446d-971c-6e86c821efb1)

**Comment by wanyaland** [comment] 2020-07-13 10:14
@nirupamav clarification on 2 issues:-
Issue 2. Significance of firstname and lastname comes in when a user has no LFID and the details are used in sending an email .
Issue 5. The CLA Manager info that is used is the manager that was adding the new CLA Manager and its alerting prospective manager to alert him when creation of an LFID is done.
Shall work on the other issues

**Comment by nirupamav** [comment] 2020-07-15 07:36
**_Verified and observed that Issue1, Issue3 and Issue5 are fixed. However observed below issues_**

**1. When clicked on the Accept Invite link in the email, user is redirected to 404 page and immediately LFX login page is displayed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d446afe2-e551-4372-b475-dcd2e0a4f683) 

**2. Invite Email format is different from other emails. Also Accept Invite link should be inside the email body and not after Thanks note**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/76748d6c-3da7-4a05-9b2c-9309d10f9b9a)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bac8e4dd-d8a0-4ddd-9dc5-6699d7d00c0e)

**Previous email format**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0a450b04-a743-4b4a-bfe8-06339d445936)

**3. Appropriate error message is not displayed when invalid email format is provided**
**_Example1_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/601b4c03-a1d6-4840-8c58-3f97d6b1d000)

**_Example2_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/10c4df31-58af-4b24-be22-cd5bd15b6efe)

**Comment by nirupamav** [comment] 2020-07-20 06:27
**_All the above mentioned are still reproducible_**
**1. Observed that this time User is redirected to page to to click on Accept the Invitation. However before the user can click that button, user is redirected to Login page**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3a5e99d7-17d6-4d03-b160-ed9b29f6913a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/43b5befd-682f-4426-9cdd-63699dc41717)

**2. Invite Email format is different from other emails. Also Accept Invite link should be inside the email body and not after Thanks note. **

**3. Email format is invalid but error message in the response says that user does not have LFID**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/53b0a017-ab67-4a95-b46b-162f3481557b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/96fa5a4f-376d-4eef-aa93-ddec5856b8a5)

**Comment by nirupamav** [comment] 2020-07-21 11:46
Invite Flow ticket in IAM
https://jira.linuxfoundation.org/browse/IAM-933

**Comment by wanyaland** [comment] 2020-07-30 16:47
@nirumpav > Can we close this and reopen one for invite flow ?

**Comment by nirupamav** [comment] 2020-08-17 07:41
Not able to validate Issue3 and invite flow due to bugs #1564 and #1560. Once they are fixed will validate the flows and if reproducible will log another bug
Except for these issues all other issues are fixed and hence moving the ticket to QA Done

**Closed** 2020-08-29 00:48 UTC
Labels: 01 - High, API, Project page for EasyCLA in V2, enhancement, v2
