### ISSUE TITLE
EasyCLA Bug Report on gRPC

### ISSUE THREAD

**Issue by caniszczyk** [communitybridge/easycla#1037] opened 2020-04-30 19:15 UTC
https://github.com/grpc/grpc-go/pull/3581

**Comment by dealako** [comment] 2020-04-30 19:33
The issue is related to the GH API call - not using authenticated API call limits us to 60 queries per hour. Working on a resolution to use an authenticated API call to avoid this issue.

**Comment by dfawley** [comment] 2020-04-30 20:42
This also affected https://github.com/grpc/grpc-go/pull/3583

**Comment by dealako** [comment] 2020-04-30 21:25
Created and Merged PR #1038

Created release: https://github.com/communitybridge/easycla/releases/tag/v1.0.20 which includes this fix. Deployed to PROD.

Awaiting feedback/confirmation of fix in PROD.

**Comment by WillsonHG** [comment] 2020-05-05 18:55
We think we know the root cause for this and we will be testing and pushing a fix for this issue hopefully later today/tomorrow.

**Comment by dealako** [comment] 2020-05-11 20:33
Status update is now working with the latest release of EasyCLA. The referenced PR is still open for grpc, but EasyCLA is working fine now.  Closing the Issue as it is resolved.

**Closed by dealako** 2020-05-11 20:33 UTC
Labels: 01 - High, API, bug, size:X-Small
