### ISSUE TITLE
Use GitHub sso don't force creation of a separate account

### ISSUE THREAD

**Issue by kapilt** [communitybridge/easycla#3446] opened 2022-02-16 11:36 UTC
for users that are already signed in via GitHub and are contributing to a project to It support login via GitHub sso.

its a very poor user experience contributing to a project to force someone to create a brand new account / credentials.

**Comment by dealako** [comment] 2022-02-16 18:44
@kapilt when a user needs to sign a given CLA, the CLA workflow takes the user through an authorization step. The user must agree to allow the EasyCLA tool to read the user's username and public email address (if shared).  The user isn't required to create a new account.  See step 4 in this workflow: https://docs.linuxfoundation.org/lfx/easycla/v2-current/contributors/individual-contributor

Did you experience something different?  If so, can you share more details?

**Comment by WillsonHG** [comment] 2023-02-07 02:02
I'll close this since it's true that contributors are not required to create any new LF login accounts to pass their PR. The bot is checking their commit for the author information, and the biggest issue we've seen is that their commit isn't linked to their github user, thereby failing the EasyCLA check. Since this is by design and well documented https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user, I'll close the issue.

**Closed by WillsonHG** 2023-02-07 02:02 UTC
Labels: enhancement, CommunityReported
