### ISSUE TITLE
Staging: Email is not received for CLA Manager during the new user invite flow for CCLA

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2355] opened 2020-12-18 13:00 UTC
Pre-Condition: Have a PR which is gated by easyCLA

Steps:

1. Login to Github and click on 'Not Covered' button
2. Select CCLA
3. Enter a new org name OR an existing org name
4. Choose 'No' for I am a CLA Manager
5. Enter Name and Email. The user should not have LFID so email should be a new one which never existed in the system.  
I tried twice for: 
Repo: avdec18org-repo1 | Email: ashav+ashishdec18@proximabiz.com | GH Username: ashishthakur42
Repo: avdec18org-repo1 | Email: ashav+staging+sw+avdec+mgr@proximabiz.com | GH Username: JyotiM362

6. It confirms email sent to the <email>
7. Check for the email

Actual Result: Email is not received. 
Expected Result: Email should be sent to the CLA Manager. 

![CCLA-EmailMsg.jpg](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/07e382d4-d662-45a6-a3fa-426aa4ea8c06)

**Comment by dealako** [comment] 2020-12-18 15:15
This issue requires support from IT services to have staging email configured properly.  Blocked until the platform core services and IT work out the solution.

**Comment by vinod-kadam** [comment] 2020-12-18 16:56
As updated by @dealako , he got a slack message from Nirav that this should get fixed today.

**Comment by dealako** [comment] 2020-12-18 20:06
@niravpatel27 has reported that this is now resolved. Confirmed in STAGING.

![Screen Shot 2020-12-18 at 12.02.24 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/f48bba2f-0ed6-480f-907f-cd4875991690)

**Comment by dealako** [comment] 2020-12-18 20:07
Closing this issue since I was able to confirm it in staging.

**Closed by dealako** 2020-12-18 20:07 UTC
Labels: API, blocked, bug, tier-1, v2

**Comment by ashav-github** [comment] 2020-12-22 11:21
I have also tested on Stage and received email. Tested scenario "CCLA->Select existing org->Select No for CLA Manager"

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/444e7375-8621-4fa8-87d9-4508d14b1dea)
