### ISSUE TITLE
Moved repository shows status 'expected'

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3408] opened 2022-02-01 16:54 UTC
When a repository is moved from one GitHub organization to another, the EasyCLA system will mark the repo as 'disabled' and then create another entry in the database with the new organization path and 'enable' that entry. However, since the GitHub repository ID remains the same, this creates two entries in the repositories table with the same github repository_external_id. This causes EasyCLA to be unable to report a status until the repository_external_id is removed from the 'disabled' entry.

https://github.com/cloudfoundry/bosh-disaster-recovery-acceptance-tests/pull/35

**Comment by WillsonHG** [comment] 2022-02-03 20:27
recommend removing the repository_external_id from the old record.

**Comment by WillsonHG** [comment] 2022-02-09 21:15
This could be related to 3393 and the 'enabled' flag.

**Comment by thakurveerendras** [comment] 2022-12-16 07:53
Tested issue with below steps on dev site & found following behaviour 
Steps 

1. Login admin portal
2. Search & open project
3. Add cla group & add GitHub organization
4. Cla enforced repo
5. Go to GitHub & moved repo to another organization 
6. Go to PCC , Easycla source control page & refresh page

Issues obtains : 
1. Moved repository is still listed with disabled state 
2. GitHub organization connection lost 
3. Install GitHub Organization APP button appears 

Refer screenshot for more details 
![image](https://user-images.githubusercontent.com/75417507/208049645-b332a9f0-0037-437d-98ef-1090c89d48c0.png)

Refer video clip for more details 

[3408.webm](https://user-images.githubusercontent.com/75417507/208050066-4eed7e48-e473-493c-93a9-fc35133ae455.webm)

**Comment by nickmango** [comment] 2022-12-16 08:47
@thakurveerendras @WillsonHG was referring to status update on a Pull request thats not working as expected due to duplicate records for the moved repository.

**Comment by thakurveerendras** [comment] 2022-12-16 11:55
Added separate ticket for frontend case , Kindly refer issue id [PCC-2666](https://jira.linuxfoundation.org/browse/PCC-2666)
CC: @amolsontakke3576 , @nickmango

**Comment by nickmango** [comment] 2022-12-16 14:56
> Added separate ticket for frontend case , Kindly refer issue id [PCC-2666](https://jira.linuxfoundation.org/browse/PCC-2666) CC: @amolsontakke3576 , @nickmango

Noted

**Comment by nickmango** [comment] 2022-12-16 18:30
@WillsonHG I was unable to reproduce this issue and so guess this should have been resolved in one of the changes since the issue was raised. I was able to reproduce @thakurveerendras use case on PCC though

**Comment by WillsonHG** [comment] 2023-02-07 00:06
Can we have QA confirm if this is still an issue? 
Test steps
Have 2 github orgs.
Have easycla installed on 1 repo in 1 org - open a PR
Move the repo to the 2nd org. Open a PR
Observe status 'expected' for easycla.
Observe 2 entries in the DB, one disabled, one enabled.
Observe that by manually removing the esxternal_repository_id in the disabled entry, the next PR succeeds in posting an easycla status.

**Comment by WillsonHG** [comment] 2023-03-27 14:37
https://github.com/communitybridge/easycla/issues/3843 This affected some CNCF repos

@dealako  this seems like low hanging fruit for a quick fix.

**Comment by thakurveerendras** [comment] 2023-05-02 13:35
Tested issue on dev site & found that it is fixed as expected. Now for "repository_external_id" "repository_organization_name" updated properly & duplicate records are not created.


- **Enforce CLA toggle on repository will remain on after transfer organization, & records are properly updated at cla-dev-repositories table** , 

Refer video clip :  

[Enforce CLA_On.webm](https://user-images.githubusercontent.com/75417507/235681711-104f7b07-2969-463e-abfd-a19db22551fc.webm)


- **Enforce CLA toggle off repository will remain off after transfer organization, & records are properly updated at cla-dev-repositories table** , 

Refer video clip : 
[Enforce CLA_Off.webm](https://user-images.githubusercontent.com/75417507/235681768-c199a063-8753-4f0e-b144-b3e6b7c216c3.webm)

**Comment by mlehotskylf** [comment] 2024-02-02 07:40
@thakurveerendras can we close this?

**Comment by mlehotskylf** [comment] 2024-02-02 07:59
@thakurveerendras confirmed this can be closed.

**Closed by mlehotskylf** 2024-02-02 07:59 UTC
Labels: bug, CommunityReported
