### ISSUE TITLE
Selecting another Signatory flow is not working

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#4247] opened 2024-02-16 16:38 UTC
## Summary

Assigning another person as SIgnatory, the flow doesn't complete after the Signatory completes the signature.

## Background

1. Access CLA Corporate Console
2. Start Signature process.
3. When asked "" Are you authorized to sign the CLA for your organization", select No
4. Add the Name and Email for the signatory person
5. The page spins forever
6. The signatory person receives a docusign email
7. The signatory completes the signature 
8. Nothing happens

## Expected behavior

After the signatory completes the signature the following must happen, but it doesn't after v2.0.150 release

1. The CCLA gets updated in the signatures table. Marked as signed=true, docusing data, signatory date.
2. The signed PDF gets uploaded to S3 bucket.
3. The Initial CLA Manager receives an email with the signatory completion
4. The initial CLA Manager gets the cla-manager role

## Screenshots

Adding the Signatory person spins endlessly:

![Image](https://github.com/communitybridge/easycla/assets/93140557/32d3d044-b056-467a-81f2-65ef8830cd14)

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x ] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by thakurveerendras** [comment] 2024-02-19 16:30
Issue is working fine on dev site but on prod we are getting 500 server error for "RequestCorporateSignatureResult"
> {
    "data": {
        "requestCorporateSignature": {
            "code": 500,
            "message": null,
            "success": false,
            "data": null,
            "__typename": "RequestCorporateSignatureResult"
        }
    }
}

![image](https://github.com/communitybridge/easycla/assets/75417507/9eaf6106-ca53-4d2a-afcd-e762430864b9)

- Refer video clip for dev:[another Signatory.webm](https://github.com/communitybridge/easycla/assets/75417507/15dd4ba4-50fb-40f2-9ff2-b5521092eb9a)

**Comment by sjparkinson** [comment] 2024-02-20 15:21
Worth noting the Docusign is still sent to the recipient. I accidently sent it more than once as a result!

**Comment by mlehotskylf** [comment] 2024-02-21 16:35
@nickmango is looking into this.

**Comment by jarias-lfx** [comment] 2024-02-21 16:40
```
{
    "data": {
        "requestCorporateSignature": {
            "code": 500,
            "message": null,
            "success": false,
            "data": null,
            "__typename": "RequestCorporateSignatureResult"
        }
    }
}
```

**Comment by nickmango** [comment] 2024-02-21 21:20
@thakurveerendras This has been resolved. Kindly verfiy

**Comment by thakurveerendras** [comment] 2024-02-22 09:37
@nickmango , The Issue is not reproducible as reported on the dev site, But after completing the signup easycla page is not loaded properly 

- Refer to the video clip: 

https://github.com/communitybridge/easycla/assets/75417507/332f50e7-ed46-4fe3-a378-33dff5194bf2

**Comment by nickmango** [comment] 2024-02-22 10:57
@thakurveerendras  
The CCLA gets updated in the signatures table. Marked as signed=true, docusing data, signatory date.
The signed PDF gets uploaded to S3 bucket.
The Initial CLA Manager receives an email with the signatory completion
The initial CLA Manager gets the cla-manager role

Werent these expectations met ?

**Comment by thakurveerendras** [comment] 2024-02-22 11:59
Tested with the documents received at email but after signing the document, CCLAs remain not signed 
Refer to the video clip: 

https://github.com/communitybridge/easycla/assets/75417507/55287919-e3e5-4dde-865f-b23d58afa6eb


![image](https://github.com/communitybridge/easycla/assets/75417507/28ced493-584c-4e47-b918-de6fea9091b2)

**Comment by mlehotskylf** [comment] 2024-02-26 16:38
"500 response" issue is resolved, now @nickmango is working on callback issue as part of this ticket.

**Comment by nickmango** [comment] 2024-02-27 15:26
@thakurveerendras kindly verify

**Comment by thakurveerendras** [comment] 2024-02-28 07:39
Tested this issue on the dev site at the parent & child project level and found that it is fixed as expected. So updating the issue status
 

https://github.com/communitybridge/easycla/assets/75417507/8e60903e-7df0-417a-8726-5e5414622265

**Comment by thakurveerendras** [comment] 2024-02-28 10:47
Tested on the prod site and found that it is deployed properly. So moving issue status QA-Done
Refer to the video clip 
[4247_prod.webm](https://github.com/communitybridge/easycla/assets/75417507/60310400-6bc6-46a0-83f9-9bfe4ff4eecc)

**Closed by thakurveerendras** 2024-02-28 10:47 UTC
Labels: bug, 01 - High, CommunityReported, CNCF
