### ISSUE TITLE
Contributor Console: Button for contributors should be disabled until CLA group info loads

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3283] opened 2021-09-14 18:53 UTC
In the contributor console, when a user is gated and clicks to sign the CLA, the program attempts to load the cla group and the UI shows a loading screen with a spinner. The buttons are greyed out, but they are still clickable. If the user clicks the button before the cla group information has loaded, the user will receive an error:

The Individual CLA option is not enabled for this project. Please to your administrator to enable the Individual CLA option for this project.

![image](https://user-images.githubusercontent.com/46732999/133316679-258f7589-5b30-4c48-be82-5d0e15ddd7b2.png)

**Comment by WillsonHG** [comment] 2021-09-14 19:07
https://api.easycla.lfx.linuxfoundation.org/v2/project/d8cead54-92b7-48c5-a2c8-b1e295e8f7f1

**Comment by dealako** [comment] 2021-09-14 20:12
Query on this endpoint in local mode took *11 seconds*. This is the python API endpoint.  This is an unauthenticated GET API endpoint used (primarily?) by the contributor console.

Consider moving to the golang backend. We do have a similar endpoint in the EasyCLA v2 API:

{{EASYCLA_v2_API_PROD}}/project/:claGroupID

This endpoint returns results much faster, *541ms* ...however:

- this endpoint is currently authenticated - this means that users must log in to the LFX platform/auth0 and be assigned the project scope for the project before they can invoke and access the results. This is currently not possible when users are simply coming to the contributor console from GitHub or GitLab.
- additionally, the response model is different. If we switched to this endpoint, we would need to update the contributor console logic to ensure: 1) all the data is returned from the v2 API endpoint, 2) data bindings are updated so that the console leverages the new response model structure

**Comment by WillsonHG** [comment] 2023-02-07 22:34
[SUPPORT-16038](https://jira.linuxfoundation.org/browse/SUPPORT-16038)

**Comment by mlehotskylf** [comment] 2024-05-06 20:28
Corresponding Support ticket [SUPPORT-16038](https://jira.linuxfoundation.org/browse/SUPPORT-16038) seems to be resolved.
@WillsonHG , can we close this ticket?

**Comment by mlehotskylf** [comment] 2024-05-29 16:28
@nickmango is this reproducible?

**Comment by mlehotskylf** [comment] 2024-06-04 15:42
This is already fixed and closing. @WillsonHG please let us know if you have any concerns.

**Closed by mlehotskylf** 2024-06-04 15:42 UTC
Labels: bug, CommunityReported
