### ISSUE TITLE
[Regression] V2 - Corporate Console - CLA Manager role is not assigned to cla manager designee who signed CLA

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1792] opened 2020-09-11 13:27 UTC
1. Create CLA Group at foundation level
2. Assign cla manager designee
3. As cla manager designee sign CLA for the project from corporate console
4. Observed that CLA Manager role is not assigned to cla manager designee who signed CLA. Due to this issue not able to add/delete cla manager and not able to add/delete approval criteria

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e119e422-9265-44a8-b8a8-6edcb9b8fe7b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e68bbc7f-defb-47a8-866e-45d378de808f)

**Comment by nirupamav** [comment] 2020-09-16 12:27
Tested for Project level and observed same issue
![image](https://user-images.githubusercontent.com/60865903/93336849-ee242700-f845-11ea-99a5-b7216669e45c.png)
![image](https://user-images.githubusercontent.com/60865903/93336973-1dd32f00-f846-11ea-980d-64c560ab2ec5.png)

**Comment by nirupamav** [comment] 2020-09-16 12:52
The behavior is very in consistent. Sometimes issue is seen for foundation level and sometimes for project level.

**Comment by dealako** [comment] 2020-09-17 04:43
Cleaned up and added a ton of debugging. The assignment of the cla-manager and removal of cla-manager-designee is called from the Database trigger when the Signatures record is updated to indicate signed=true.  Upon this event, the record is evaluated and:

1. Signed On date field is added
1. if CCLA
   1. company record is loaded
   1. `cla-manager` role is assigned to the initial CLA manager
      1. User is searched by via LF Username
      1. User is searched by LF Email
      1. User is searched by Alternative Emails
      1. CLA Group -> Project Mappings are loaded
      1. `cla-manager` role assigned for each ProjectSFID + CompanySFID
   1. CLA Group -> Project Mappings are loaded
   1. (New) `cla-manager-designee` roles are removed for all users who were assigned this role for ProjectSFID + CompanySFID

**Comment by dealako** [comment] 2020-09-17 04:45
@nirupamav Created PR and pushed to DEV. Needed to deploy since the trigger is accomplished via a DB update event.  Need to construct and validate a test scenario.  I will do this...unless you have a nice automated script.

For this one, the log details will be in: DEV `us-east-2` easycla-api cloudwatch log

**Comment by nirupamav** [comment] 2020-09-17 12:47
@dealako 
I have automated script to validate this scenario. I ran the scripts today and observed that the issue is still reproducible

**Comment by rinkeshbhutwala** [comment] 2020-10-19 09:48
@nirupamav I have verified this ticket looks like the issue is resolved so moving this ticket to QA.

**Comment by nirupamav** [comment] 2020-10-19 10:20
Executed the automated scripts and Verified that the issue is fixed

**Closed** 2020-10-21 23:02 UTC
Labels: 01 - High, API, Corporate Console for V2, Regression, v2
