### ISSUE TITLE
Corporate console allows contributor to send themselves an email and sign CCLA

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#555] opened 2020-02-05 06:18 UTC
## Summary

Look at this video at 01:45 
https://zoom.us/rec/share/-o9sCrPz0iRJG5338hvYS_N6Pt7qaaa8gSMdq6BYmEyXDMjZoUzNzs-tDheDygrF

You will see that muktipeeda@gmail.com who is the contributor can only select his own email to send a CCLA signing request. What this means is that a contributor is signing CCLA when they are not authorized to sign the CCLA. 
This form should allow the contributor to type the name and email address of the CLA Manager for their company.

## Background

https://www.lucidchart.com/documents/edit/0f9041ff-b287-426a-b441-bfdff7e42840/0?callback=close&name=docs&callback_type=back&v=1221&s=612

This problem is happening at step 4a. 

## Expected behavior

Modal window should allow the contributor to type the name and email of CLA Manager or CLA Signatory from their company who can sign CLA. 

## Screenshots

Look at this video at 01:45 
https://zoom.us/rec/share/-o9sCrPz0iRJG5338hvYS_N6Pt7qaaa8gSMdq6BYmEyXDMjZoUzNzs-tDheDygrF

## Additional Context

This problem has happened before in production with OSQuery project where a Google contributor couldn't type the email address of Google CLA Manager and got stuck at this screen.

## Acceptance Criteria

- [  ] Modal window allows contributor the type the email address and name of a CLA Manager or CLA Signatory. 
- [  ] Modal window should explain that contributor needs to send an email to CLA Manager or CLA Signatory who can sign CCLA for this project on behalf of their company and then they will be whitelisted.

**Comment by WillsonHG** [comment] 2020-02-05 15:23
That modal window actually says "Select the email address attached to your account that you would like your company's cla manager to whitelist." So it's sending an email to the "company administrator" which in easycla terms would be a cla manager on file (which one ???) for the company (for another project). The email being populated is telling the "administrator" who the request is from. 

Steve's comment "Step 4a: This is incorrect: if the company exists already, but has not yet signed the CCLA, then the next step is Step 3 -- so we can ask them who should be the CLA Manager from their company for this project, and then proceed with the same CCLA signing workflow."

**Comment by dealako** [comment] 2020-02-05 22:12
Per @pranab-bajpai this is not a bug. Closing this ticket as part of the product backlog review meeting.

**Closed by dealako** 2020-02-05 22:12 UTC
Labels: 01 - High, Console - Contrib, bug
