### ISSUE TITLE
Allow project-specific CLA managers for signee companies

### ISSUE THREAD

**Issue by christopherclark** [communitybridge/easycla#334] opened 2019-11-09 00:09 UTC
Company CLA managers in large companies aren't able to pick which projects they manage CLA approvals for. Think about a company like IBM, and how they participate in a ton of LF projects. Some of the participation is within the same group within IBM, but some is in completely distinct parts of the org. There should be a "default" option for one or more default CLA admins, but the company should be able to tag certain CLA admins as only being responsible for specific projects. When notifications go out, it should only notify those that care about the specific request.

Currently, anyone requesting to be affiliated with IBM's CCLA would trigger emails to 8 separate people who are listed as CLA managers. Please add capability to mitigate these excess emails and allow for more granular CLA management.

**Comment by dealako** [comment] 2019-11-26 01:26
We are working on a new modal dialog which allows the contributor to select one of the CLA admins for their company under the project.  We need to confirm that this new workflow resolves this feature request.

**Comment by pranab-bajpai** [comment] 2019-12-03 21:10
This issue is duplicated by #383 since solving that will ensure CLA Managers are only concerned with their projects. Need to discuss during backlog grooming.

**Comment by KennyPaul** [comment] 2019-12-06 18:03
Not sure that this is truly a duplicate of  https://github.com/communitybridge/easycla/issues/383 as a key part of this is bug is about notifications sent to CCLA managers.  Perhaps fixing the ACLs may also fix this, but an ACL != "add me" request emails.

**Comment by mlehotskylf** [comment] 2024-02-02 07:07
@nickmango please review this ticket.

**Comment by mlehotskylf** [comment] 2024-05-06 20:57
This is no longer applicable since we are using V2 now.

**Closed by mlehotskylf** 2024-05-06 20:57 UTC
Labels: enhancement, 03 - Med, size:TBD, needs-investigation
