### ISSUE TITLE
GitHub organization approval criteria stopped working

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#4229] opened 2024-02-02 19:00 UTC
## Summary

Starting 2024-02-02 EasyCLA is not longer working for companies using GitHub Organization as the approval criteria

## Background

Some companies use GitHub organization as the approval criteria, as long as the contributors are part of the GitHub Organization and the organization is public, EasyCLA should just ask the contributors for the acknowledgement. Starting 2024-02-02 the contributor now show with approved = false. Event when marking the user manually approved = true in the signatures table. It changes back to approved = false on PR update.

The Event appear as follows:
```
{
 "event_id": "c9323621-d0d7-4322-9db0-599fb4d5ebc5",
 "contains_pii": true,
 "date_created": "2024-02-02T18:40:41.672327+0000",
 "date_modified": "2024-02-02T18:43:36.425073+0000",
 "event_cla_group_name": "Cloud Foundry - Series LLCs",
 "event_cla_group_name_lower": "cloud foundry - series llcs",
 "event_company_id": "c02e9bdb-199e-44d3-a54f-9d94dfd7cddc",
 "event_company_name": "SAP",
 "event_company_name_lower": "sap",
 "event_company_sfid": "0014100000Te0dnAAB",
 "event_data": "The employee signature of user None was disapproved the during CCLA check for project Cloud Foundry - Series LLCs and company SAP",
 "event_data_lower": "the employee signature of user none was disapproved the during ccla check for project cloud foundry - series llcs and company sap",
 "event_date": "02-02-2024",
 "event_date_and_contains_pii": "02-02-2024#true",
 "event_project_name": "undefined",
 "event_project_name_lower": "undefined",
 "event_project_sfid": "a092M00001IkUMrQAN",
 "event_summary": "The employee signature of user None was disapproved the during CCLA check for project Cloud Foundry - Series LLCs and company SAP",
 "event_time": "2024-02-02T18:40:41.677328+0000",
 "event_time_epoch": 1706899241,
 "event_type": "EmployeeSignatureDisapproved",
 "event_user_id": "3cb03123-512b-48ff-8647-6091972d33ea",
 "version": "v1"
}
```

## Expected behavior

EasyCLA shouldn't change the ECLA to approved=false automatically.

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [ x ] PROD 
* Browser:
  - [ x ] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by jarias-lfx** [comment] 2024-02-02 19:10
Affected PRs:

- https://github.com/cloudfoundry/community/pull/769
- https://github.com/paketo-buildpacks/libpak/pull/301
- https://github.com/cloudfoundry/cloud_controller_ng/pull/3623
- https://github.com/cloudfoundry/cloud_controller_ng/pull/3618
- https://github.com/cloudfoundry/uaa/pull/2704

**Comment by mlehotskylf** [comment] 2024-02-03 01:44
The issue has been resolved. The root cause was an invalid GitHub token, which had either expired or been invalidated. We created a new GitHub token using the user account `EasyCLA-Machine-User`, which does not expire. After updating the GitHub token in the PROD, some of the previously failing PRs above still encountered issues. Upon further investigation, I found that the `signature_approved` field in the `signatures` table in DynamoDB was set to `FALSE` for users. By manually setting this field to TRUE for the users `silvestre` and `c0d1ngm0nk3y`, all the affected PRs successfully passed the CLA check.

**Comment by thakurveerendras** [comment] 2024-02-05 09:26
Tested the fix on production at the "Test Project IT" project & found that I can add & update the GitHub user name under approval list
![image](https://github.com/communitybridge/easycla/assets/75417507/2f26c08e-660c-45fa-bc97-288618bae0fc)

**Comment by thakurveerendras** [comment] 2024-02-05 09:28
![image](https://github.com/communitybridge/easycla/assets/75417507/3a60db30-063d-40b7-8b0a-5fc9f7b6fc05)

**Comment by mlehotskylf** [comment] 2024-02-05 20:25
@jarias-lfx please confirm this is working as expected so we can close this ticket.
Thanks!

**Comment by jarias-lfx** [comment] 2024-02-05 20:43
Confirmed working.

**Comment by jarias-lfx** [comment] 2024-02-06 14:25
Seen issue on https://github.com/pytorch/pytorch/pull/117845

**Closed** 2024-02-06 14:42 UTC
Labels: bug, 01 - High
