### ISSUE TITLE
Individual CLA Signature Download

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1230] opened 2020-06-13 00:21 UTC
## Summary

Download Individual Signatures for this CLA Group as a PDF file

## Background

For a description of the services needed, view the [Project Console PRD](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2).

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the DEV environment.

## References

- [Project Console PRD](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2)

**Comment by prasannamahajan** [comment] 2020-06-29 07:27
Duplicate of https://github.com/communitybridge/easycla/issues/1320

**Closed** 2020-06-29 07:26 UTC
Labels: API, Project Console V2, v2
