### ISSUE TITLE
Project Console : Getting error while creating CLA template 

### ISSUE THREAD

**Issue by kdhaigud** [communitybridge/easycla#499] opened 2020-01-15 10:16 UTC
## Summary

While creating template in Mozilla browser then template is not displayed
where as in chrome browser its giving error message while creating template

## Background

1. Go to 'https://project.dev.lfcla.com'
2. Configure github organization
3. Create CLA group
4. Click on select template
5. Enter project details 
6. Click on done

## Screenshots

User should be able to create CLA template

## Environment

* Environment: Dev
[screencast-www.google.co.in-2020.01.zip](https://github.com/communitybridge/easycla/files/4064316/screencast-www.google.co.in-2020.01.zip)
![Screenshot from 2020-01-15 15-45-44](https://user-images.githubusercontent.com/52558085/72425637-30c0cb80-37ae-11ea-991f-eb42d39a2d65.png)
![Screenshot from 2020-01-15 14-51-53](https://user-images.githubusercontent.com/52558085/72425655-39190680-37ae-11ea-8ac8-196799e81786.png)

* OS: Ubuntu
* Browser : [chrome, Mozilla]

**Comment by WillsonHG** [comment] 2020-02-19 20:18
The pdf preview in FF is not working on dev, stage, or Prod. You can create the pdf template with firefox in prod, but the button to view does nothing. If you hit "done" and go back to the cla group view, refresh, and select to view the newly created templates- a window flashes for a moment then disappears. 

You can then switch to chrome and you are able to view the newly created template pdf's.

**Comment by dealako** [comment] 2020-02-26 18:33
Duplicates #594

**Comment by dealako** [comment] 2020-02-26 18:33
Closing this one as this is a duplicate of #594

**Closed by dealako** 2020-02-26 18:33 UTC
Labels: bug
