### ISSUE TITLE
Pull Request Bot Comment Review for Corporate Contributor

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1043] opened 2020-05-01 22:02 UTC
## Summary

Review the bot comment for a user without an ICLA and a company with a CCLA on file in a github pull request.

## Background
1. create a github pull request and be gated by easycla bot.
1. EasyCLA checks the user and finds them in the Approved list of a company, but the user needs to verify (no ccla signature on file)
1. Bot posts comment 
![image](https://user-images.githubusercontent.com/46732999/80845408-1aad0e80-8bd7-11ea-9056-d144b2c3608a.png)

1. User verifies with their company. 
1. Cla checks and finds ccla and updates checks in bottom section of PR as success, but does not update the previous failure comment. 
![image](https://user-images.githubusercontent.com/46732999/80845473-521bbb00-8bd7-11ea-98dc-6959b2213a42.png)

## Expected behavior

Once the contributor verifies with their company and easycla finds the signature entry, the bot comment should be edited to show success. 
![image](https://user-images.githubusercontent.com/46732999/80844505-b721e180-8bd4-11ea-8db6-20bb4d5ab92b.png)
The language in the failure comment also needs to be proofed for correct spacing and changed to "Approved List".

## Environment
prod

## Acceptance Criteria
- [x] The text of the comment needs to be changed to read "[github user] is in the company's Approved List, but they must confirm their affiliation with that company. Start by clicking here, choose "Corporate", select your company from the list, and then confirm your affiliation on the page that appears." 
- [x] In addition to the above text, add a sentence to the end with a link to the service desk. "For further assistance with EasyCLA, please submit a support request ticket." The "please submit a support request ticket." section should link to 
https://jira.linuxfoundation.org/servicedesk/customer/portal/4
- [ ] After the contributor verifies their affiliation to their company and the status reports a success, the comment should be edited to show the success comment 
![image](https://user-images.githubusercontent.com/46732999/80844505-b721e180-8bd4-11ea-8db6-20bb4d5ab92b.png)

**Comment by dealako** [comment] 2020-05-06 21:40
Added help desk link as part of: https://github.com/communitybridge/easycla/pull/1080

**Comment by dealako** [comment] 2020-05-07 16:23
It could be a refresh issue that is now resolved due to our updated check logic (which is now faster and doesn't look through all the signature on file).

For the last acceptance criteria:

1. User is gated in GH - no employee signature on file
1. User is in the "Approved List" by email/domain/gh user whatever but needs to be affiliated with a company
1. EasyCLA sends the appropriate status update saying they need to be affiliated with their company
1. All good
1. The user goes into contributor console, and affiliates with their company
1. The logic that refreshes the PR:
   1. Updates the Check
   1. DOES NOT update the comment ----> this is what needs to be updated

**Comment by nirupamav** [comment] 2020-05-14 11:35
@WillsonHG 
Since the issue is related @722 Should we reopen this or should we close this ticket

**Comment by WillsonHG** [comment] 2020-05-14 14:51
I want to keep this open.

**Comment by dealako** [comment] 2020-05-15 22:11
Still need to resolve: "After the contributor verifies their affiliation to their company and the status reports a success, the comment should be edited to show the success comment"

**Comment by WillsonHG** [comment] 2020-06-01 20:50
A good example of how the comment should change from fail to passing is in the logs here https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/cla-backend-prod-githubactivity;stream=2020/06/01/%5B$LATEST%5D08b18bc037e14a3f8cc611ba6e39dd2a;start=2020-05-31T20:40:37Z

20:38:58
2020-06-01T20:38:58 INFO cla: Getting comment body for repository type: github
2020-06-01T20:38:58 INFO cla: Getting comment body for repository type: github

20:38:58
2020-06-01T20:38:58 DEBUG cla: Found previously failed checks - updating CLA comment in PR.
2020-06-01T20:38:58 DEBUG cla: Found previously failed checks - updating CLA comment in PR.

20:38:59
2020-06-01T20:38:59 DEBUG cla: Found matching CLA comment for PR: 1644
2020-06-01T20:38:59 DEBUG cla: Found matching CLA comment for PR: 1644

20:38:59
2020-06-01T20:38:59 DEBUG cla: Updating existing CLA comment for PR: 1644 with body: [![CLA Check](https://s3.amazonaws.com/cla-project-logo-prod/cla-signed.png)](https://lfcla.com)<br />The committers are authorized under a signed CLA.<ul><li>:white_check_mark: dependabot[bot] (7ea61703407d025d23f21817f94fbf6aca0f1153)</li></ul>
2020-06-01T20:38:59 DEBUG cla: Updating existing CLA comment for PR: 1644 with body: [![CLA Check](https://s3.amazonaws.com/cla-project-logo-prod/cla-signed.png)](https://lfcla.com)<br />The committers are authorized under a signed CLA.<ul><li>:white_check_mark:  dependabot[bot] (7ea61703407d025d23f21817f94fbf6aca0f1153)</li></ul>

20:38:59
2020-06-01T20:38:59 DEBUG cla: EasyCLA App checks pass for PR: 1644 with authors: [('7ea61703407d025d23f21817f94fbf6aca0f1153', 'dependabot[bot]')]
2020-06-01T20:38:59 DEBUG cla: EasyCLA App checks pass for PR: 1644 with authors: [('7ea61703407d025d23f21817f94fbf6aca0f1153', 'dependabot[bot]')]

20:38:59
2020-06-01T20:38:59 DEBUG cla: Creating new CLA status on commit 7ea61703407d025d23f21817f94fbf6aca0f1153: success
2020-06-01T20:38:59 DEBUG cla: Creating new CLA status on commit 7ea61703407d025d23f21817f94fbf6aca0f1153: success

20:39:00
2020-06-01T20:39:00 INFO cla: Successfully posted status on PR 1644: Commit 7ea61703407d025d23f21817f94fbf6aca0f1153
2020-06-01T20:39:00 INFO cla: Successfully posted status on PR 1644: Commit 7ea61703407d025d23f21817f94fbf6aca0f1153

**Comment by WillsonHG** [comment] 2020-08-05 21:17
https://github.com/cloudfoundry-incubator/eirini-release/pull/170

https://github.com/open-telemetry/opentelemetry-cpp/pull/195

**Comment by dealako** [comment] 2020-08-06 19:06
Updated logic - see https://github.com/communitybridge/easycla/pull/1532

- Resolved case where previous GitHub failed comment was not being updated

**Comment by dealako** [comment] 2020-08-06 19:08
Pushed to DEV

**Comment by nirupamav** [comment] 2020-08-07 10:02
Testing blocked due to #1533

**Comment by nirupamav** [comment] 2020-08-17 08:24
**_When contributor is authorized and contributor confirms affiliation with the company. Also contributor userid exists in EasyCLA DB_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b82a3585-9c54-414e-a03e-d48fc0e014a6)


**_When contributor is authorized and contributor confirms affiliation with the company. Also contributor userid does not exist in EasyCLA DB_**

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5058b1b3-7053-4b08-9fd1-17a789089903)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7fe8517f-f7f0-4e7a-aa96-0e0e67981c3f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/200b0596-4e64-4067-a8e5-aa0c730d6b72)

**Closed** 2020-08-29 00:48 UTC
Labels: 02 - Med High, HOTFIX_PROD, bug
