### ISSUE TITLE
Using GitHub revert pulls all the commits involved in the revert and not the actual commits in the PR

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3926] opened 2023-05-04 22:04 UTC
## Summary

When using GitHub Revert option EasyCLA decided to pull all the commits involved in the revert and not the actual commits in the PR.

## Background

This issue was experienced in PR: https://github.com/sonic-net/sonic-mgmt/pull/8213. GitHub Revert option was used and EasyCLA pulled all the commits involved in the revert:
![image](https://user-images.githubusercontent.com/93140557/236339527-32dffffe-0d05-4120-a6eb-e9e54f5041d4.png)
Not the actual commits in the PR.
This was fixed using "/easycla" comment

## Expected behavior

Using GitHub revert should pull only the current commits in the PR.

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by mlehotskylf** [comment] 2024-05-08 15:43
This is working as expected since this is the way EasyCLA handles reverts. Closing this as "not a bug".

**Closed by mlehotskylf** 2024-05-08 15:43 UTC
Labels: bug, CommunityReported
