### ISSUE TITLE
DocuSign send the document from David Deal account

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#4248] opened 2024-02-16 16:54 UTC
## Summary

DocuSign is sending the document email using David Deal's account

## Background

During the signature process, We send am email to the contributor or signatory with the DocuSign information, this is currently being sent from David Deal's account.

## Expected behavior

The information should be sent from LF Engineering

## Screenshots

![image](https://github.com/communitybridge/easycla/assets/93140557/794b31ed-8253-4915-a277-3e5f1b2aaac0)

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by dealako** [comment] 2024-02-16 19:34
@mlehotskylf @nickmango - we may need to adjust the DocuSign integration to leverage/use the LF user_id instead of my DocuSign account (my account was used to create the new integration).

Please review and confirm the following configuration settings:

- User ID: c2d31780-94da-4948-94a7-e9ec84fed103 (ddeal)
- User ID: 8597969e-e099-4d82-80c1-1ed9aadfe624 (LF Admin)

**Comment by mlehotskylf** [comment] 2024-02-16 21:21
Thank you @dealako for your comment. We are currently using ddeal's User ID (c2d31780-94da-4948-94a7-e9ec84fed103) and we will replace it with LF Admin's ID 8597969e-e099-4d82-80c1-1ed9aadfe624 in AWS Parameter Store.

**Comment by mlehotskylf** [comment] 2024-02-17 00:42
Thank you @dealako for your help with this issue. I have working User ID now, but this issue is not resolved yet, because I don't have permission to update it in SSM in PROD. We also need to manually update this value for each 25+ EasyCLA lambdas, or simply re-deploy EasyCLA's lambdas to pickup updated SSM value. I already sent heads to 
Chandrasekhar from DevOps and asked him if he can update it as a first thing on Monday morning IST. Once it is updated I will ask @thakurveerendras to validate it in PROD.

**Comment by mlehotskylf** [comment] 2024-02-19 05:55
I just want to add that we will be using User ID `*****ad9fe6` which is for the user `docucla@linuxfoundation.org`. I tested it in Postman and it works file.

**Comment by mlehotskylf** [comment] 2024-02-19 07:40
@dealako we updated `User ID` in AWS Parameter Store but the problem is that new User ID belongs to "`CLA Integration User - PROD`" and this name is showing up now. Although this naming is an improvement over the previous one, I believe this name should be more "human friendly".

@WillsonHG I believe you helped us to accept "consent" and you have access to this `CLA Integration User - PROD` user (docucla@linuxfoundation.org) in DocuSign, do you know if it is possible to rename it?

Thank you both for your help!!!

![Screenshot 2024-02-18 at 11 23 50 PM](https://github.com/communitybridge/easycla/assets/49538656/48bdc715-3355-4a71-8508-700b4dd8031f)
![Screenshot 2024-02-18 at 11 26 58 PM](https://github.com/communitybridge/easycla/assets/49538656/04be7b01-e993-4cb5-bb8d-890cffa3921e)

**Comment by WillsonHG** [comment] 2024-02-20 15:29
Hello @mlehotskylf  The current name for that user is "CLA User", so I don't think it's pulling from the profile name.
![image](https://github.com/communitybridge/easycla/assets/46732999/b71c0157-ddb2-452f-b30e-cb390043b441)

Regardless, I've changed it to LFX EasyCLA since that's more appropriate.

**Comment by thakurveerendras** [comment] 2024-02-20 16:49
@mlehotskylf , @dealako 
LFX **`Integration`** EasyCLA appears while expected **LFX EasyCLA**, Kindly review

![image](https://github.com/communitybridge/easycla/assets/75417507/8dbc93da-c80b-4fae-a2d3-9eaf5094e6c7)

**Comment by mlehotskylf** [comment] 2024-02-28 05:02
@thakurveerendras This should be adjusted and name should not include word `Integration` anymore, and it should be just "LFX EasyCLA". Can you please verify?

**Comment by thakurveerendras** [comment] 2024-02-28 05:09
Tested issue on prod and found that proper "**LFX EasyCLA**" appears at DocuSign page 
![image](https://github.com/communitybridge/easycla/assets/75417507/e24927c6-1e51-4efa-b348-7a29a210702e)

**Comment by mlehotskylf** [comment] 2024-06-04 16:14
This is done, closing.

**Closed by mlehotskylf** 2024-06-04 16:14 UTC
Labels: bug, 01 - High
