### ISSUE TITLE
V2 API (top-companies API Endpoint): Random data is fetched when companies have same count for claManagersCount/corporateContributorsCount/projectsCount

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#858] opened 2020-04-10 16:04 UTC
## Background

1. Fetch the response for https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/metrics/top-companies
2. Observed that random records are fetched when same count exists for multiple companies
![image](https://user-images.githubusercontent.com/60865903/79004756-08f5bf80-7b73-11ea-9af5-331e3c9f9340.png)

**Comment by prasannamahajan** [comment] 2020-04-13 11:53
Pull Request : https://github.com/communitybridge/easycla/pull/864
If count is same then sorting metrics by CompanyName

**Comment by nirupamav** [comment] 2020-04-14 10:16
**_Triggered lambda function to get latest metrics and verified that each time records are fetched as below_**

- topCompaniesByClaManagers are fetched based on claManagersCount
- When few companies among top 5 companies of topCompaniesByClaManagers have same claManagersCount then records are fetched based on claManagersCount and ordered by company name
- topCompaniesByProjectCount are fetched based on projectsCount
- When few companies among top 5 companies of topCompaniesByProjectCount have same projectsCount then records are fetched based on projectsCount and ordered by company name

**_Could not test topCompaniesByCorporateContributors as I cannot contribute to existing companies that fetched in the top 5 companies of topCompaniesByCorporateContributors. Also I do not have more than 50 github accounts to test this issue_**

**Comment by wanyaland** [comment] 2020-12-23 22:06
Verified metrics returning record by checking dynamo records for cla-dev-metrics and cla-dev-signatures tables

**Comment by vinod-kadam** [comment] 2020-12-28 16:31
@dealako  to look at it & make a decision.
This API doesn't seem to be used by Corporate Console.

**Comment by dealako** [comment] 2022-08-22 15:56
We are closing this issue for now. If the issue is observed, this ticket can be re-opened or a new ticket created.

**Closed by dealako** 2022-08-22 15:56 UTC
Labels: bug
