### ISSUE TITLE
Project Console : While configuring second organisation "Add GitHub Organization " pop up is not getting open

### ISSUE THREAD

**Issue by kdhaigud** [communitybridge/easycla#500] opened 2020-01-15 10:25 UTC
## Summary

User can configure multiple organisation but when user tries to configure second organisation Add GitHub Organisation pop up is not getting open 
## Background

1. Go to 'https://project.dev.lfcla.com'
2. Click on Connect Github organisation
3. "Add github organization" pop up gets open
4. Enter organisation name
5. Click on connect
6. Organisation should get configure
7. Again click on Connect Github organisation
8.  "Add github organization" pop up is not getting open

## Expected behavior

"Add github organization" pop up should get open as many time user click on  Connect Github organisation
## Screenshots

[Connect Github organisation pop up.zip](https://github.com/communitybridge/easycla/files/4064363/Connect.Github.organisation.pop.up.zip)

**Comment by WillsonHG** [comment] 2020-02-19 20:23
I was unable to reproduce this on dev or prod. This may have been a caching issue.

**Comment by dealako** [comment] 2020-02-26 19:56
Let's close this for now. If needed, we can re-open if the problem persists.

**Closed by dealako** 2020-02-26 19:56 UTC
Labels: Console - Proj, bug, size:TBD, v1
