### ISSUE TITLE
Management Console: Company Search Function non-functional

### ISSUE THREAD

**Issue by KennyPaul** [communitybridge/easycla#590] opened 2020-02-18 22:09 UTC
## Summary

In the Management Console using the search function does not appear to work

## Background
From Managemenrt Console:

- select project name
- select "view companies" from either the menu or the button
- enter a company name in the search box in the pop-up window
- click search
- optional: select "Full Match" toggle and click search

Results are not company specific and seem to be random as differing results seem to be produced with each click of the search button

## Expected behavior
User should get results matching that company

## Screenshots
![image](https://user-images.githubusercontent.com/44849153/74781856-313dfd80-5257-11ea-9db9-5ef372b61794.png)

![image](https://user-images.githubusercontent.com/44849153/74781949-63e7f600-5257-11ea-93d1-88e2315212b3.png)

![image](https://user-images.githubusercontent.com/44849153/74782051-9c87cf80-5257-11ea-92d3-3133fa2cf543.png)

![image](https://user-images.githubusercontent.com/44849153/74782124-c2ad6f80-5257-11ea-964c-53012b4e9704.png)

## Environment
Production

## Acceptance Criteria
- Search results are limited to companies matching the search criteria

**Comment by WillsonHG** [comment] 2020-02-19 16:37
#580

**Comment by dealako** [comment] 2020-02-19 18:10
Duplicate of #580 - closing during the backlog review meeting.

**Closed by dealako** 2020-02-19 18:10 UTC
Labels: bug, duplicate
