### ISSUE TITLE
Issue with Gerrit Project Whitelisting

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#305] opened 2019-10-28 16:57 UTC
**Summary**
For some Gerrit projects, some companies experience consistent issues in whitelisting their employees
Project(s) experiencing most issues listed first:
- ONAP (https://gerrit.onap.org)
   - Companies experiencing the most issues
       - Amdocs (@amdocs.com): most recent user: `3aa8c272-2600-47f6-b6bc-2cd60c761b48`
       - AT&T (@att.com, @research.att.com)
- ORAN-SC
   - Companies experiencing the most issues
       - China Mobile (@chinamobile.com)

**Background**
1. Go to https://gerrit.onap.org/
1. Click on 'Settings' cog in the top-right corner
1. Click on 'Agreements' link in left nav near the bottom of the list
1. See list of agreements or options to sign CLA.

**Expected behavior**
When a user does at least one of the following:
1. Signs ICLA
1. Confirms affiliation with the company that whitelisted them
-----------
The following 4 things are expected:
1. Signature record on `cla-*-signatures` table is added for individual (`Consistently Failing`)
1. User's LFID is added to the appropriate CLA group (`Consistently Failing`)
    - Here are the following LDAP CLA groups currently using EasyCLA:
        - tf-cla-icla
        - oran-cla-icla
        - oran-cla-ccla
        - oran-cla-oss-icla
        - oran-cla-oss-ccla
        - [onap-cla-ccla](https://identity.linuxfoundation.org/group/node/1902/admin/people)
        - [onap-cla-icla](https://identity.linuxfoundation.org/group/node/1903/admin/people)
1. User sees the appropriate agreements listed on Gerrit (Settings > Agreements) (`Consistently Failing`)
1. **User is able to commit code**

**Screenshots**
Gerrit (Settings > Agreements)
![image](https://user-images.githubusercontent.com/51214959/67700061-3e1ea480-f97b-11e9-8d9b-e4fb85c27a89.png)

**Environment**
 - Environment: PROD
 - OS: Catalina
 - Browser: Chrome
 - Version: 77.0.3865.120

**Additional Context**
Most recent users experiencing the issue with ONAP
 - `3aa8c272-2600-47f6-b6bc-2cd60c761b48`
 - `d9882d77-4791-483b-9346-27a76a66d7a4`

**Acceptance Criteria**
The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**
Gerrit Walkthrough Video: https://youtu.be/XQcRBuIPQVY
[Onboarding Details](https://confluence.linuxfoundation.org/display/PROD/Project+Onboarding+Details+and+Status)
Possible support resources
 - @aric (#Slack) - ORAN 
 - @emsearcy (#Slack) - LDAP APIs (Parental Leave)
 - @tykeal (#Slack) - LDAP CLA Groups

**Comment by dealako** [comment] 2019-12-31 01:35
Needs investigation with engineering write-up.

**Comment by WillsonHG** [comment] 2020-01-17 20:57
So in looking at the first user referenced, 3aa8c272-2600-47f6-b6bc-2cd60c761b48 has a signature == false in db. The logs from that timestamp show easycla was unable to match his email to the whitelist even though it was clearly present. This could have been related to the issue that Harold has just fixed with the whitelisting RexEx. It did not give the same error, though. https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/cla-backend-prod-apiv2;stream=2019/10/24/%5B$LATEST%5D400c0a8b68fe45a3bdcbf21e4c0818bb;refid=35055707993933873043134812050630404224553086700832555020;reftime=1571952312887

The second user put in a ticket about this https://jira.linuxfoundation.org/browse/SUPPORT-659 he had the wrong email on file in gerrit, the company had whitelisted a different email for him, so that was working as intended.

There are no other examples listed. I will look back through my tickets to identify any other issues related.

**Comment by wanyaland** [comment] 2020-01-21 14:23
@WillsonHG , So if these happen to be the only examples the whitelisting functionality is working fine ?

**Comment by WillsonHG** [comment] 2020-01-21 16:07
@wanyaland  I think there still may be a problem. The first example 3aa8c272-2600-47f6-b6bc-2cd60c761b48 failed an individual email whitelist check, even though it should have passed. 

I am currently looking back through the tickets from October and there are a few tickets from that time that I think may be related. I'll post them as I investigate.

**Closed** 2020-01-22 17:06 UTC
Labels: 02 - Med High, Console - Contrib, bug, needs-investigation, v1
