### ISSUE TITLE
V2 - Request Authorization email content issues

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1258] opened 2020-06-16 14:07 UTC
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the project

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and Select the Company
9. Click Proceed
10. Click on Request Authorization for the CLA Manager
11. Request is submitted and email is sent to the CLA Manager
12. Observed below issues in email content
- Links in the email are pointing to V1 url's
- Contributor message is displayed, however there is no option in the contributor console for the contributor to enter message. Is the message harcoded?
- Steps to be followed to add contributor to approved list for V1 and not V2 UI
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4ee7c345-4200-480b-8ed2-2ae2fe0ecfb2)

**Comment by dealako** [comment] 2020-07-22 22:52
@nirupamav will investigate. I searched the code and didn't find anything hard-coded with the message text.

**Comment by dealako** [comment] 2020-08-10 23:27
@rinkeshbhutwala can you coordinate with @nirupamav to determine if this issue is still valid?

**Comment by nirupamav** [comment] 2020-08-13 14:21
@rinkeshbhutwala 
I observed that email format has been changed and above issues are fixed. However observed below issues

1. CLA group name is displayed instead of project name
2. Contributor email Id is not displayed (Contributor email is not public in Github. But how can the CLA Manager add the contributor to approval list? In this case will the CLA Manager be forced to add by github username?)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5c09ff18-9257-40db-b8e5-0db89ecfa8bf)

**Comment by dealako** [comment] 2020-08-13 16:05
Try to include the user's email, if available.

**Comment by dealako** [comment] 2020-08-13 19:58
This API call seems to be called by the v2 Contributor Console.  At this point, the contributor console only has access to the CLA Group Name - not projects attached to this CLA Group.  I am updating the email content, the API, and the UI clearly indicate it's the CLA Group.

Created PR: https://github.com/communitybridge/easycla/pull/1566
and
v2 Corporate Console PR: https://github.com/communitybridge/easycla-contributor-console/pull/75

The email will contain as much information as we can gather from the user record. If we were able to extract the email, then the email will be added to the UI. @nirupamav LMK what you think about this: getUserFormattedDetails: https://github.com/communitybridge/easycla/pull/1566/files#diff-a86df26658aee4920dd2c86606e16c64R886

**Comment by dealako** [comment] 2020-08-13 20:40
Merged PR's

**Comment by nirupamav** [comment] 2020-08-14 07:02
**Verified and observed that contributor emails are displayed in the email notification irrespective of whether github user emails is public or not**

**Github user with public email**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f9e0aaca-1ab9-4783-84f8-65828a4bcf94)

**Github user without public email**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/63a84f18-2aa8-4342-8964-5ed1d5b908e3)

**Comment by dealako** [comment] 2020-08-20 00:12
QA confirmed - closing issue.

**Closed by dealako** 2020-08-20 00:12 UTC
