### ISSUE TITLE
CLA Corporate Console - Search not working correctly

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3749] opened 2023-02-03 21:19 UTC
Details
Reporter: Bob Killen, Google

The URL of where it occurred: organization.lfx.linuxfoundation.org

The approximate time when the issue occurred: any

The Datadog Session Replay: not applicable

Error Message: none

Steps to Reproduce
Setup:
Test Organization
Test CLA Manager
Signed CLA on Test Project
Many contributor acknowledgements

Steps:
Contributor Acknowledgements from My organization section:
use the search box to find a user who clearly shows on the first page. 
Observe it fails if searching for the Name
Observe it fails if searching for the LF Login/GitHubID

Expected Result:
We should return results for either column, case insensitive
We should paginate this section.

**Comment by WillsonHG** [comment] 2023-02-03 21:21
https://jira.linuxfoundation.org/browse/LFX-3198

**Comment by WillsonHG** [comment] 2023-02-07 00:31
@mrbobbytables This is related to https://github.com/communitybridge/easycla/issues/3501 and will be fixed in tandem. Will provide an ETA soon.

**Comment by thakurveerendras** [comment] 2023-07-07 10:49
Hello @nickmango 
Issue is still reproducible at production as reported, So making issue status QA-Failed
![image](https://github.com/communitybridge/easycla/assets/75417507/cbb1bd12-0480-469f-9556-0fb1130418b1)

**Comment by mlehotskylf** [comment] 2024-02-02 06:55
@nickmango please review this ticket.

**Comment by nickmango** [comment] 2024-03-08 17:02
For this issue .. Pagination was added for the contributor acknowledgements and is working as expected. @jarias-lfx Kindly requesting access for the CNCF project(Google org) to be able to reproduce this issue on the UI front and confirm the failed case reported by @thakurveerendras 
cc @mlehotskylf

**Comment by mrbobbytables** [comment] 2024-03-08 17:51
I did a quick test, search did work for the "Contributor Acknowledgements From My Organization" 🎉 

BUT "Approved List of Contributors From My Organization" just comes up as None, even before attempting to search. It's been awhile since I've logged into the console, so I honestly don't remember if it was like that before or not. >_<

![Screenshot 2024-03-08 at 11 48 33 AM](https://github.com/communitybridge/easycla/assets/6500863/543d3eb4-33f0-4c98-8d67-a0127f4d1729)

**Comment by wanyaland** [comment] 2024-03-08 17:58
Thanks for the clarification search working should close this issue .
For the approval list of contributors there was an enhancement that
affected the performance and that should have been resolved at the moment.
Can you kindly verify the latest checks.
I’ll be moving this to QA in the meantime for the search issue raised

**Comment by mrbobbytables** [comment] 2024-03-08 18:18
Tried it again, also in a separate browser and the "Approved List of Contributors From My Organization" does still come up as `None`.

**Comment by mrbobbytables** [comment] 2024-03-08 18:22
Search DID work for it 👍

**Comment by wanyaland** [comment] 2024-03-08 18:31
Thanks. I will look into the approval list issue and get back to you

**Comment by nickmango** [comment] 2024-03-09 00:00
@thakurveerendras moving this to QA . Kindly re-verify the search as its not reproducible as confirmed by @mrbobbytables

**Comment by mlehotskylf** [comment] 2024-03-13 15:49
This is still reproducible for CNCF, we are investigating.

**Comment by jarias-lfx** [comment] 2024-03-13 16:07
Confirmed the search API is working as expected. The previous comment was related to a data issue caused by the v1-v2 migration a couple of years ago, specifically for LFX organization.

**Comment by mlehotskylf** [comment] 2024-03-14 15:54
This is data issue and it is impacting only old records which don't have data populated certain values for the search to apply on.
Closing do to very limited impact.

**Closed by mlehotskylf** 2024-03-14 15:54 UTC
Labels: bug, CommunityReported, CNCF
