### ISSUE TITLE
Contributor Acknowledgements From My Organization for Project EasyCLA page

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#939] opened 2020-04-19 22:55 UTC
## Summary
Any user associated with a company will be taken to this page after they switch to member console, select project from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/Dfbd923b389bffae1192a3a2ca50c3faa)for the project page for EasyCLA.

![image](https://user-images.githubusercontent.com/57362064/79701977-d892dd00-8266-11ea-80af-5a06d9fbbc4f.png)

Step 5 in PRD 
https://confluence.linuxfoundation.org/display/PROD/Project+Dashboard+for+EasyCLA

**Contributor Acknowledgements From My Organization**

**This is a view only table. Table shows contributors from my company associated with this project who have completed contributor acknowledgments.** 

**Name** i.e. the contributor name along with photo of the individual (from individual profile page if available).
**LFID/GHID** is the LinuxFoundation ID or GitHub ID of the contributor.
**Agreement version** of CLA agreement that was signed by this contributor.
**Timestamp** i.e. date and time when this user acknowledged.

## Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1 or Sev. 2  bug(s)

**Comment by nirupamav** [comment] 2020-05-27 12:39
testing blocked due to #1140

**Comment by dealako** [comment] 2020-05-29 23:24
@nirupamav resolved 1140 - please re-evaluate.

**Comment by nirupamav** [comment] 2020-06-01 12:17
**_Tested and observed below issues. Testing with different roles is still Inprogress_**
1. **The contributor that contributed for the company has the account in userservice, but still the name and linux_foundation_id is not fetched in the response**
**IAM setup**
![image](https://user-images.githubusercontent.com/60865903/83403167-c55a5c00-a425-11ea-94f0-577beb1cc63e.png)

**Response**
![image](https://user-images.githubusercontent.com/60865903/83403188-d2774b00-a425-11ea-81e6-c5ea6ef13a0b.png)

**UI API call in network tab**
![image](https://user-images.githubusercontent.com/60865903/83403585-a27c7780-a426-11ea-8367-df7313ae588a.png)

2.  **Able to fetch contributors for project when the user does not have access to the project
As per below screenshot user has access to only Brigade project but is able to fetch contributors for CRI-O. Actually 403 should be returned**
![image](https://user-images.githubusercontent.com/60865903/83404411-3ef34980-a428-11ea-80d8-af1cb3c48302.png)

3. **401 is returned when trying to fetch contributors for company when the user does no have access  to the company. Actually 403 has to be returned. @dealako as confirmed this in #1135** 

4. **CLA group details are not available in response**

5. **When projectid is not provided in the endpoint URL, 403 is returned. 400 should be returned with appropriate error message**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project//contributors

6. **When companyid is not provided in the endpoint URL, 403 is returned. 400 should be returned with appropriate error message**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company//project/a092M00001IV4PgQAL/contributors

7. **When invalid companyid is provided in the endpoint URL, 401 is returned, 404 should be returned with appropriate error message**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/gdgfd/project/a092M00001IV4PgQAL/contributors

8. **When invalid projectid is provided in the endpoint URL, 200 is returned with empty response. 404 should be returned with appropriate error message**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/fgfdh/contributors

**Comment by vinod-kadam** [comment] 2020-11-30 17:54
David to evaluate it.

**Comment by dealako** [comment] 2020-11-30 23:59
@rinkeshbhutwala please review this ticket. There are several things to review on the API side - in terms of permissions and appropriate responses.

Given this is for the Organization Dashboard (Corporate Console), they should be able to handle API errors appropriately.

- point 1 - I'm not understanding which API she is referring to.
- point 2 and 3 - not authorized should return 403
- point 4 - can you determine why the CLA Group is not returned in the response payload. Is this by design or an error encoding the details in the response?
- point 5 and 6 - If missing or malformed parameters to the API, then a 400 Bad Request should be returned.
- point 7 and 8 - if an invalid or non-existent company_id is provided, then a 404 should be returned

**Comment by rinkeshbhutwala** [comment] 2020-12-01 15:13
@dealako I have tested and verify this ticket and below is my observation.

The ticket is related to below mention endpoint also gone through the given PRD.

https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectContributors

point 1 - Here API call is a direct call to DynamoDB there is no call between user-service so it's not returning the LFID and name of that user. 
point 2 & 3 - Working fine as expected and return 403 if it is not in scope.
point 4 - I am not sure why we need cla group details and there is nothing we show as per PRD on that screen related to cla-group.
point 5 & 6 - If the path variable like project-SFID or company-SFID is not provided then it should return 404 which is as expected.
point 7 & 8 - If we provide an invalid project-SFID or company-SFID it should check first with permission user haven't access to given ID's then it will give 403.

Let me know it is fine or give you a suggestion on that one.

**Comment by dealako** [comment] 2020-12-01 15:29
Thanks for clarifying. Let's close this issue.

**Closed by dealako** 2020-12-01 15:29 UTC
Labels: 01 - High, API, Project page for EasyCLA in V2, enhancement, tier-1, v2
