### ISSUE TITLE
Staging - After unenrolling the project from CLA Group, Admin is unable to view the Signatures of unenrolled project. 

### ISSUE THREAD

**Issue by ashav-test** [communitybridge/easycla#2326] opened 2020-12-15 12:05 UTC
Steps:

1. Have a CLA Group with project having some signatures.
2. Login to Admin Console, click on project and go to Tools->CLA
3. Unenroll the projects from CLA group.
4. Now, click on Signatures button

Actual Result: It throws error:
queryName:"getIclaSignatures"
error:"{"Code":"403","Message":"EasyCLA - 403 Forbidden - user is not authorized to view project ICLA signatures any scope of project","x-request-id":"29ea5b80-3ecb-11eb-904e-27147587375d"}"
errorLoggedTime:"Tue, Dec 15th 2020, 5:16:29 pm IST"

![UnenrolledProject-Signature.jpg](https://images.zenhubusercontent.com/5fa00bff91c622ed8feb9f29/aea9ba5e-aa5f-4874-b43e-94e22100b8b4)

Expected Result: As discussed with @dealako after project unenrollment, historical data should be available for Admin to access.

**Comment by vinod-kadam** [comment] 2020-12-15 13:11
@dealako& @pranab-bajpai , I have set it as EasyCLAv2Release & marked it as tier-2 however lets discuss it in today's standup whether it should be downgraded to tier-3.
Current reason: on enrollment, permission for that user is taken away. However if that user adds that project to another cla group, permissions are restored to that user.

**Comment by dealako** [comment] 2020-12-16 01:17
I am having trouble re-producing this in DEV...

**Comment by vinod-kadam** [comment] 2020-12-16 07:14
As updated by @dealako  to @rinkeshbhutwala , Rinkesh is going to try to reproduce this issue with help of Asha.

**Comment by vinod-kadam** [comment] 2020-12-16 13:09
As updated by @rinkeshbhutwala, he is not able to reproduce the issue with his projects. However, if he uses Asha's project he is able to see the issue - might be a data issue. From code perspective, things look fine.
Rinkesh to work with Asha on this one.

**Comment by ashav-github** [comment] 2020-12-16 14:59
@dealako @vinod-kadam had discussion with @rinkeshbhutwala and we tried different scenarios. Its observed that in case of Foundation level CLA group it works fine. But, in case of project level cla group this issue is reproducible. 
Rinkesh is looking into this further.

**Comment by rinkeshbhutwala** [comment] 2020-12-17 05:21
@vinod-kadam We have checking permission with the given projectSFID loop through the cla-group mapping table and while we unenroll the project-level cla-group so we deleted the entry from the mapping table and we are not able to find that entry so it's giving an error.

Added support for checking permission for project-level cla-group.

**Comment by vinod-kadam** [comment] 2020-12-17 15:31
@ashav-github  is testing this one.

**Comment by ashav-github** [comment] 2020-12-17 17:25
@dealako @rinkeshbhutwala @wanyaland  I tested on Stage and still able to reproduce the issue. I created a new project group 'Christmas Foundation' and a project inside it. Created a CLA group 'santa-clagrp'.  After unenrolling the project, when Admin clicks on Signature, ut throws below error:
queryName:"getEmployeeSignatures"
error:"{"Message":"provided project is not associated with cla_group","x-request-id":"e664f560-408b-11eb-904e-27147587375d"}"
errorLoggedTime:"Thu, Dec 17th 2020, 10:48:37 pm IST"

Here is the screen shot:

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/b72dbf23-2980-4dd2-bcf8-72915ccc729e)

**Comment by vinod-kadam** [comment] 2020-12-18 16:48
As discussed in the standup with @dealako and @pranab-bajpai , following was decided.
Disable Approved contributors "View All" button when there are no projects associated with the CLA group.

**Comment by tejasadg** [comment] 2020-12-21 07:29
PR link https://github.com/LF-Engineering/admin-console/pull/493

**Comment by manishv09** [comment] 2020-12-22 12:16
I verified this ticket on DEV environment to test and found working for both the old test data and New one.
Please the few screencast for reference and complete workflow tested in attached doc file.
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b26aa217-b22e-4b8e-9cb4-54934cfceb83)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/fb70b0bd-6bae-43b5-ae00-d244ce900c6e)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/4a4745c8-f880-49ba-8212-eb7f804c6f2f)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/99025263-246a-439e-9926-6daef4938bd4)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/0002c333-2d98-4e41-affd-bd8def377680)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/72271a17-c9fe-4abf-bfa3-36267fd47275)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b203fb8b-0038-4f07-8f1a-07d2472e5395)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/6941456d-6c78-4ac2-87fd-28c3ca1f2359)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/28cac6b5-4e50-4f31-9ed9-00f67699806f)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/1bb34ac6-a08f-4191-8d65-a07ca2e31a7b)
[https://app.zenhub.com/files/194341141/40eecf58-6f80-45dc-8b87-83dbb83f0825/download](https://app.zenhub.com/files/194341141/40eecf58-6f80-45dc-8b87-83dbb83f0825/download)

**Closed** 2020-12-24 13:24 UTC
Labels: bug, tier-2, v2
