### ISSUE TITLE
"Invalid Managed Token ID and / or secret" is displayed while trying to sign document

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#728] opened 2020-03-23 11:38 UTC
## Background
1. Launch github repository for which CLA is configured
2. Login as developer/Individual contributor
3. Edit some file
4. Create PR
5. Click on CLA NOT SIGNED button
6. User is redirected to Contributor Console
7. Click on Individual
8. Click Open CLA
9. Observed Login page for DocuSign is displayed with below error message
_**Facing this issue only for one user (github username nirupamav). Tried to login with github credentials but says "Invalid email and / or password"**_
![image](https://user-images.githubusercontent.com/60865903/77312306-c1280900-6d27-11ea-91e8-21f96479ae49.png)

**Comment by dealako** [comment] 2020-03-25 18:15
@WillsonHG please review

**Comment by WillsonHG** [comment] 2020-03-25 22:08
@dealako I was unable to reproduce this issue with my github user on dev.

**Comment by WillsonHG** [comment] 2020-03-25 22:10
https://github.com/CLATestOrg/adetest/pull/7 
The pr i was testing from.

**Comment by WillsonHG** [comment] 2020-03-26 16:23
today, reproduced it in same pr and with a new pr. on both a brand new firefox that i had never logged into github or docusign. and in a incognito chrome, and in a regular chrome with cache.

**Comment by dealako** [comment] 2020-04-27 16:10
One issue is that we have a sandbox docusign account for DEV and STAGING - I currently do not have a login to the Docusign console for this account.

1) we could use the production docusign account for DEV and STAGINg as well (probably not preferred)
2) create a new Docusign sandbox account, share credentials with the team, and adjust the SSM docusign tokens so that we use this account when testing (preferred)
3) how to get access to the existing sandbox account??

**Comment by sanatChoubey** [comment] 2020-10-09 05:17
Hey, Getting the same issue when tried to use envelopeView Url in incognito mode is this happen because of the sandbox account?

**Comment by dealako** [comment] 2021-07-24 20:00
This issue appears to be resolved. Closing ticket.

**Closed by dealako** 2021-07-24 20:00 UTC
Labels: Console - Contrib, bug, needs-investigation, v1
