### ISSUE TITLE
V2 - Need API to edit CLA Group Name and Description

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1622] opened 2020-08-20 07:22 UTC
As of now there is no option to edit CLA Group name and description. Need an API to CLA Group name and description and update the name where ever applicable
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0e9f035d-1ad8-4bf4-9ae9-7b42c60aead4)

**Comment by dealako** [comment] 2020-10-03 00:21
Created PR: https://github.com/communitybridge/easycla/pull/1920/files

**Comment by dealako** [comment] 2020-10-03 00:41
Update API: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/updateClaGroup

**Comment by nirupamav** [comment] 2020-10-05 05:46
**_Tested and observed below issues_**
**1. Endpoint is not added to ACS file and hence only system-admin has access to the endpoint**
https://github.com/LF-Engineering/acs-cli/blob/master/services/11-cla-service.yaml

**2. When no body is provided 500 is returned**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b473717d-b450-4c3f-9d33-6d70523b2b7e)

**3. Able to update the CLA Group name with already existing CLA Group name.**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7a74fa91-7b3c-473c-8a2f-f0000e233a0c)

`Existing CLA Group Name`
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a4395d8a-be0d-456b-823e-1b7145816c0d)

**Comment by dealako** [comment] 2020-10-05 21:09
Added ACS-CLI PR to add permissions to the API-GW/ACS: https://github.com/LF-Engineering/acs-cli/pull/318

**Comment by dealako** [comment] 2020-10-05 21:25
Merged PR - deploying to DEV.

**Comment by dealako** [comment] 2020-10-05 22:07
Creating PR for duplicate or missing parameters: https://github.com/communitybridge/easycla/pull/1926

**Comment by nirupamav** [comment] 2020-10-06 09:17
**Issue3 is still reproducible and observed another issue. All other issues are fixed. Verfied Issue with only project manager role. Other roles will be verified in #1933**

3. Able to update the CLA Group name with already existing CLA Group name
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/26bcd810-748e-4259-ae3c-ebd0d81bf3b3)

**4. Duplicate description is not allowed. Description should not be restricted**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/168cd200-d3e4-4c15-964b-181235049bf7)

**Comment by dealako** [comment] 2020-10-06 19:56
Sorry, @nirupamav. I'm unable to reproduce the duplicate name allowed scenario. Can we review this issue during our next standup? I want to review your test scenario details.

**Comment by nirupamav** [comment] 2020-10-07 13:55
@dealako 
I am still able to reproduce the issue. Below is the data in cla-dev-projects table and getCLAGroup is fetching data from cla-dev-projects table. However in cla-dev-projects-cla-groups old cla group name is displayed
![image](https://user-images.githubusercontent.com/60865903/95340238-8a37d000-08d2-11eb-9cd7-92bc824098f7.png)

![image](https://user-images.githubusercontent.com/60865903/95340381-b3f0f700-08d2-11eb-9fc1-6ac5d117d719.png)

![image](https://user-images.githubusercontent.com/60865903/95340444-cc611180-08d2-11eb-8d61-420c7548ecb1.png)

**Comment by dealako** [comment] 2020-10-14 18:21
@nirupamav this logic was updated after discussing with @asithade. Can you please re-test?

**Comment by nirupamav** [comment] 2020-10-15 08:13
Issue is still reproducible

**CLA Group taht exist for another project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b5df9e7a-e1af-4311-927a-ee412a0f0e3d)

**Able to edit with existing cla group name**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/464759e5-a805-4bff-b166-f4c1d40b0dc2)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7b0fac42-5827-43cd-ad35-67c4dc41f3cc)

**Comment by dealako** [comment] 2020-10-16 00:24
Added additional logic. See PR: https://github.com/communitybridge/easycla/pull/1998

**Comment by nirupamav** [comment] 2020-10-16 09:16
Verified that the issue is fixed. However observed an issue where I was trying to update description including cla group name of the project, error is displayed. Logged issue #2000
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e1ca110a-cb3e-4328-8f09-b6bd86d4ef01)

**Closed** 2020-10-16 14:22 UTC
Labels: API, Project Console V2, v2
