### ISSUE TITLE
A message to inform that we need to login to connect to Github Organization and install application should be displayed

### ISSUE THREAD

**Issue by automationframework508** [communitybridge/easycla#586] opened 2020-02-17 13:08 UTC
## Summary

When we are not logged in to github and try to connect to github organization to install the application we cannot see install/configure button. I was lost for sometime as there was no note which mentioned to login to Github. Even in the steps displayed in "Connect LF CLA App to GitHub Organization" window does not mention to login.
A message to inform that we need to login to proceed further should be displayed for better usability.

![image](https://user-images.githubusercontent.com/61135378/74656544-5168b080-51b4-11ea-85ec-5d993e063676.png)

**Comment by dealako** [comment] 2020-02-19 18:48
@ngozi-ekekwe can you review this ticket - should be a quick fix.

For this issue, we should add a note for the user to ensure they are logged into GH. Coordinate with @pranab-bajpai on the text/note/warning message and how it should be displayed.

**Comment by pranab-bajpai** [comment] 2020-02-20 16:59
![image](https://user-images.githubusercontent.com/57362064/74959141-ad5b5100-53cf-11ea-9f22-ee42bf042908.png)
On this page when the user clicks on "Install GitHub CLA App" open a dialog box, with following message. 
"You are exiting EasyCLA and going to GitHub site. Please make sure you are already logged into GitHub so that you can install EasyCLA app". 
The box should display a "OK" button for the user to click and then they should go to GitHub

**Comment by amolsontakke3576** [comment] 2020-03-05 11:39
@pranab-bajpai This issue is resolved already.
@nirupamav can you please test it again ?

**Comment by nirupamav** [comment] 2020-03-05 13:20
@amolsontakke3576 
Verified that a alert message is displayed to inform user to login to Github is displayed
Verified in Chrome, Firefox and Edge browsers
![image](https://user-images.githubusercontent.com/60865903/75985234-f358fe80-5f11-11ea-8560-c0f222b06b6a.png)

**Comment by nirupamav** [comment] 2020-03-05 13:21
Closing as the issue is fixed

**Closed by nirupamav** 2020-03-05 13:21 UTC
Labels: 05 - Low, Console - Proj, bug, documentation, v1
