### ISSUE TITLE
Pending Whitelist count is not incremented when CLA is signed by the company after whitelist request

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#807] opened 2020-04-02 10:02 UTC
## Background

**Prerequisite**
1. Project **Issue627Test1** with ccla enabled should exist
2. Company **CompSignAfterEmployeeRequest** should exist and should not have signed cla

**Steps to follow**

1. Launch github repository url https://github.com/selenium-af/Issue719
2. Login as github user
3. Update any file and Pull Request
4. Checks fail
5. Click on the link to Sign CLA
6. Click on Corporate
7. Select Company **CompSignAfterEmployeeRequest**
8. Popup to request authorization is dsiplayed
10. Select employee Email ID 
![image](https://user-images.githubusercontent.com/60865903/78235602-7f9d1800-74f6-11ea-9c24-e27c641a72ca.png)

10. Click SEND button and click DISMISS
![image](https://user-images.githubusercontent.com/60865903/78235848-dc003780-74f6-11ea-9f92-1a9b2ce8c27c.png)

11. Launch Corporate Console
12. Login as nirupamav+mentee1@proximabiz.com 
13. Click on company **CompSignAfterEmployeeRequest**
14. Click SIGN NEW CLA
15. Search and Select Project **Issue627Test1**
16. Click SUBMIT
17. Click YES
18. Click OPEN CLA
19. Complete the docu sign process
20. Observed the pending request is 0 and not incremented
![image](https://user-images.githubusercontent.com/60865903/78236042-1bc71f00-74f7-11ea-8c2d-b9e368eca66e.png)

![image](https://user-images.githubusercontent.com/60865903/78236068-27b2e100-74f7-11ea-9593-b7ae8f5a962b.png)

**Comment by dealako** [comment] 2020-04-03 22:40
@wanyaland please review and diagnose. Work with @amolsontakke3576 to determine if this is a UI or backend issue.

**Comment by wanyaland** [comment] 2020-04-07 18:21
@amolsontakke3576  This will require an update on the api call on the UI. There are 2 cases
1. For a signed CLA . When a user makes a whitelist request the /v3/company/{companyID}/ccla_whitelist_requests/{projectID} endpoint is called 
2. For an unsigned CLA the legacy endpoint /v2/user/{user_id}/request-company-ccla is called . 
So for unsigned CLAs a change to invoke the v3 endpoint instead of v2 can solve the count issue

**Comment by nirupamav** [comment] 2020-04-09 07:28
**_Verified and observed that the count is incremented when the CLA is signed after whitelist request is sent_**
**_Observed message "CCLA whitelist request already exist" is displayed in contributor console even if user is requesting for the company for the first time. Logged a bug #841 to track the issue_**

**Contributor Console**
![image](https://user-images.githubusercontent.com/60865903/78867525-dce91a00-7a5e-11ea-86dd-4315dd1d1926.png)

![image](https://user-images.githubusercontent.com/60865903/78867629-043fe700-7a5f-11ea-99ed-1db2c32c0067.png)

![image](https://user-images.githubusercontent.com/60865903/78867667-0f931280-7a5f-11ea-8b55-3ef514446d24.png)

**Corporate Console**
![image](https://user-images.githubusercontent.com/60865903/78868055-d1e2b980-7a5f-11ea-90c1-f35c621c36ba.png)

![image](https://user-images.githubusercontent.com/60865903/78868188-18d0af00-7a60-11ea-8130-91a6d5d82698.png)

![image](https://user-images.githubusercontent.com/60865903/78868213-27b76180-7a60-11ea-9fff-4d41a1849213.png)

**Comment by nirupamav** [comment] 2020-07-14 08:16
Reopening the ticket as the issue is reproducible again

![image](https://user-images.githubusercontent.com/60865903/87401792-420d5800-c5d8-11ea-906b-09d2efe594e1.png)


![image](https://user-images.githubusercontent.com/60865903/87401763-36219600-c5d8-11ea-97e0-8c563d80e0af.png)

![image](https://user-images.githubusercontent.com/60865903/87401834-505b7400-c5d8-11ea-8c47-4e58891e5731.png)

**Comment by dealako** [comment] 2020-07-15 23:03
@amolsontakke3576 can you troubleshoot and diagnose this regression?  Coordinate with @nirupamav on testing this. Seek help from me or @wanyaland if you need help reviewing records in the DB.

**Comment by nirupamav** [comment] 2020-07-17 06:45
Testing blocked due to #1418

**Comment by nirupamav** [comment] 2020-07-20 06:11
Testing blocked due to #1424

**Comment by nirupamav** [comment] 2020-07-23 09:07
**Observed CORS issue while requesting authorization for company has not signed CLA. However email is sent to CLA Manager to sign CLA. When signed again observed the pending request count is not updated**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/335d9a0c-81da-4151-a2af-4b5c8d93c3d7)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f5705c58-515d-437b-8297-5f8f7cceb62a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/23744305-58fb-48c5-b2f2-19bc1979580c)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9202d8bc-b5ce-4d08-b724-10eaea40c939)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d2033943-0e96-4b41-b5a5-b688effd8332)

**Comment by dealako** [comment] 2020-07-23 23:18
The issue appears to be related to a python error:

```
[ERROR] TypeError: object of type 'UUID' has no len()
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 110, in handler
    return serverless_wsgi.handle_request(wsgi_app, event, context)
  File "/var/task/serverless_wsgi.py", line 173, in handle_request
    response = Response.from_app(app, environ)
  File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_app
    return cls(*_run_wsgi_app(app, environ, buffered))
  File "/var/task/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/var/task/hug/api.py", line 502, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
    raise
  File "falcon/api.py", line 269, in falcon.api.API.__call__
    responder(req, resp, **params)
  File "/var/task/hug/api.py", line 356, in version_router
    request, response, api_version=api_version, **kwargs
  File "/var/task/hug/interface.py", line 946, in __call__
    raise exception
  File "/var/task/hug/interface.py", line 917, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/var/task/hug/interface.py", line 839, in call_function
    return self.interface(**parameters)
  File "/var/task/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/var/task/cla/routes.py", line 184, in invite_company_admin
    project_name, company_name
  File "/var/task/cla/controllers/user.py", line 251, in invite_cla_manager
    ccla_whitelist_request.save()
  File "/var/task/cla/models/dynamo_models.py", line 3954, in save
    return self.model.save()
  File "/var/task/pynamodb/models.py", line 457, in save
    args, kwargs = self._get_save_args()
  File "/var/task/pynamodb/models.py", line 1221, in _get_save_args
    serialized = self._serialize(null_check=null_check)
  File "/var/task/pynamodb/models.py", line 1369, in _serialize
    serialized = self._serialize_value(attr, value, null_check)
  File "/var/task/pynamodb/models.py", line 1397, in _serialize_value
    serialized = attr.serialize(value)
  File "/var/task/pynamodb/attributes.py", line 418, in serialize
    if value is None or not len(value):
```

**Comment by dealako** [comment] 2020-07-24 00:02
Merged PR: https://github.com/communitybridge/easycla/pull/1470

Ready for re-test @nirupamav

**Comment by nirupamav** [comment] 2020-08-07 10:03
Testing blocked due to #1533

**Comment by nirupamav** [comment] 2020-08-17 08:06
**Verified that the issue is still reproducible**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8bd7c590-1463-48b2-a456-739bd83a0491)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/43d87dad-6ee9-4149-aace-9fa46ce83126)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6c822c34-5f6f-4376-8768-fe8cf8d9636a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d7a7be31-2f11-41ae-821a-7ac042eba891)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a66188e4-b6fc-44cf-ab4d-3ed20ec9ac7d)

**Comment by rinkeshbhutwala** [comment] 2020-10-20 11:16
@dealako I have verified this ticket and found that the issue is from the python side while we call the POST endpoint from the python side **/user/{user_id}/request-company-ccla** data is not inserted properly and the status is also shown as **Pending** 

![Screenshot from 2020-10-20 16-32-58.png](https://images.zenhubusercontent.com/5f20ee93f9a45844ef8dfce5/e212d877-4f40-47b3-92b5-d448c2e0678e)

![oie_PmZGegOQkCuu.png](https://images.zenhubusercontent.com/5f20ee93f9a45844ef8dfce5/31976701-2487-4edf-b775-6e1f300a4e1b)

**Comment by dealako** [comment] 2020-10-21 23:52
Created PR: https://github.com/communitybridge/easycla/pull/2030

**Comment by dealako** [comment] 2020-10-21 23:53
@rinkeshbhutwala sorry, but can you test this after you merge the PR?

**Comment by nirupamav** [comment] 2020-10-22 06:08
Testing Blocked due to #2032

**Comment by nirupamav** [comment] 2020-10-29 07:46
Testing blocked due to #2075

**Comment by dealako** [comment] 2022-08-22 15:57
The old v1 console is deprecated and removed.

**Closed by dealako** 2022-08-22 15:57 UTC
Labels: bug, size:Small, 03 - Med, Console - Corp, v1, API
