### ISSUE TITLE
CLA groups not shown to the ONAP

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#3603] opened 2022-10-14 09:39 UTC
- Go to the PCC dev https://pcc.dev.platform.linuxfoundation.org/
- Find the project ONAP
- Go to the EasyCLA
- You can see `No CLA Groups Available` even CLA groups are already exist.
- Click on Add new CLA group
- Error come `Cannot create CLA Group. CLA group already available for this project`

![Image](https://user-images.githubusercontent.com/56335654/195820149-5edb979f-19d3-46a2-afd5-e8fc7929e8cd.png)
![Image](https://user-images.githubusercontent.com/56335654/195820148-f1580dbb-5bb1-40f5-9125-93bdf3e8a2cc.png)

**Comment by nickmango** [comment] 2022-10-19 18:49
@amolsontakke3576 this was a data issue caused by a previous CLA group getting deleted.. Cleaned the data and refactored the logic for the deletion. I have created a new CLA Group in case you want to use that for testing

**Comment by amolsontakke3576** [comment] 2022-10-20 09:03
thanks @nickmango I will test this.

**Comment by thakurveerendras** [comment] 2023-05-28 11:19
After data clean-up issue is fixed as expected, So making issue status QA-Passed

**Comment by mlehotskylf** [comment] 2024-02-02 07:36
Done, closing.

**Closed by mlehotskylf** 2024-02-02 07:36 UTC
Labels: bug, 01 - High, backend
