### ISSUE TITLE
Unable to sign CCLA for a case where contributor identifies himself as CLA Manager and proceed for sign-in process

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2290] opened 2020-12-09 10:44 UTC
Steps:

1. Have a PR created by a contributor and he is gated.
2. Click on to sign CCLA, select an Org and identify himself as CLA Manager
3. Continue and create the new LFID, verify email and login to corporate console.
4. Click on 'Proceed to Sign' 

Actual Result: The pop-up shows error 'CLA System is not able to support your request. Please Click here to open a support ticket.' 

Expected Result: It should allow to complete the sign-in process.

![Screenshot from 2020-12-09 16-14-33.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/80e48f60-d860-4ca8-8596-c3375be99ba5)

**Comment by vinod-kadam** [comment] 2020-12-16 16:21
As discussed in the standup, Denis was not able to reproduce it.
Asha reported that she has not seen it recently; Harold reported that it was fixed indirectly while fixing other issue.

**Comment by manishv09** [comment] 2020-12-17 11:09
Verified today and found working fine, please follow the screencast below for more details:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/7b850f32-a021-4fd3-8c0b-ec1a01307234)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/1e454189-9087-4593-a515-b7a8d5e911cc)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/25923014-187e-4649-b94e-6e926176d5ab)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/0c16156d-e6e1-403d-a306-bd2d5f270737)

**Closed** 2020-12-21 06:43 UTC
Labels: tier-2, v2
