### ISSUE TITLE
Add user as a contact if the user selects not to become CLA Manager

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1806] opened 2020-09-15 14:18 UTC
![Screen Shot 2020-09-15 at 9 09 19 AM](https://user-images.githubusercontent.com/57362064/93221569-8bdb0180-f733-11ea-9056-1878d22fea2a.png)

This is to implement the red boxed area in the flow chart above.

**Comment by nirupamav** [comment] 2020-09-22 11:51
I tried below flows and observed that contact role is not assigned to the github user who started the CLA process and proceeds with the flow as not authorized CLA Manager. Tried both flows, existing company that has not signed CLA and by creating new company
Github user has LFID created with it's email
`userid in users table 3620f611-f442-404a-829e-eeb8886e2043`
Observed that there is no API call triggered for contact role assignment
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/48f97ca0-582e-46f8-8b67-07f61d205f00)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f385b9bb-8b85-4c65-9152-153df1211595)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c715c58a-d17b-4220-a45b-b2cf9405a1fe)

**Comment by wanyaland** [comment] 2020-09-22 12:57
@nirupamav updated this. The conversion to contact happens during the invite-company-admin call. And the conversion happens if user has type lead

**Comment by nirupamav** [comment] 2020-09-22 14:02
@wanyaland It is still not working
**_Tested and observed that in below scenarios contact role is not assigned_**
**1. Github user has LFID with user role. For an existing company that has not signed CLA, tried to identify an user as CLA Manager for the project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f04109cf-5b02-4661-83f0-b1255e557631)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f9c1710b-ba90-40fb-ad95-68c413a0818a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/904c0fe4-cc5a-42d3-80fe-5fbd660f6b31)

**2. Github user has LFID with user role. For an existing company that has not signed CLA, tried to identify a user who is already CLA Manager designee as CLA Manager for the project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/31a1e6f5-f89c-439c-a6c5-7bc7165ba6b4)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/36510e5a-b02c-4f3e-b7a1-41657a3ffc0a)

**3. Github user has LFID with user role. Add New company and identify CLA Manager**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/df9c730f-29f2-48aa-80c5-ed78a1c28684)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2a468b83-a771-4fa2-9cd9-2af338c8c6f3)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/89ead7df-a03d-405b-930b-8c7683adce6d)

`Github userid in cla database 3620f611-f442-404a-829e-eeb8886e2043`
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/17ae8fca-874a-48eb-be49-36b05079cf2c)

**Comment by nirupamav** [comment] 2020-09-25 12:27
The type is not converted from lead to contact. Below is the example. **_I kindly request you to not use this userid to reproduce the issue as I do not have any other user with type lead to test once you fix the issue. You can create new account and try it yourself_**

I tried below flow
```
1. Create New company
2. Identify CLA Manager designee
3. I did not find any API call for lead to contact conversion. Not sure if it is taken care in invite-company-admin or company-owner endpoints
```

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0372d813-f5e3-4d68-9692-a41a4f629c8c)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cd6d76be-3a25-49dc-be1b-6e3cd117909e)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/834e8de6-dda1-4735-a6de-e18765681cde)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/28bba736-858e-4f78-a380-0989e7e82b39)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1c23920d-3e32-4217-a8df-a361362b7ee2)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a8eeae28-63db-4ded-a010-838e146009b1)

**Comment by wanyaland** [comment] 2020-09-25 13:06
@nirupamav . This user is already a contact as seen below 
```
"Data": [
        {
            "Type": "contact",
            "ID": "0036s000003L8yRAAS",
            "FirstName": "claindividualuser2",
            "LastName": "test",
            "Name": "claindividualuser2 test",
            "Emails": [
                {
                    "Active": true,
                    "EmailAddress": "nirupamav+claindividualuser2@proximabiz.com",
                    "ID": "a2g6s0000004XPrAAM",
                    "IsDeleted": false,
                    "IsPrimary": true,
                    "IsVerified": true,
                    "SubscribedSystem": null
                }
            ],
            "Username": "claindividualuser2",
            "LastModifiedDate": "2020-09-25T11:30:24Z",
            "CreatedDate": "2020-09-14T09:32:18Z",
            "Account": {
                "ID": "0016s000004quVlAAI",
                "LogoURL": "https://lf-master-organization-logos-dev.s3.us-east-2.amazonaws.com/thelinuxfoundation.svg",
                "Name": "sep25comp13"
            },
            "Bio": "",
            "Address": {},
            "DoNotCall": false,
            "EmailOptOut": false,
            "LeadSource": "LF Auth0"
        }
    ],
    "Metadata": {
        "Offset": 0,
        "PageSize": 1,
        "TotalSize": 1
    }
}
```
So since they are contact no need for conversion. Secondly the conversion is happening during the invite-company-admin invocation and it checks if user is lead the does conversion

**Comment by nirupamav** [comment] 2020-09-25 13:09
@wanyaland 
We are supposed to make the github user who started the flow as contact and not the user who has been identified as the cla manager designee

**Comment by nirupamav** [comment] 2020-09-29 07:07
Observed that the issue is still reproducible.
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bcd909e6-872d-4e2c-8458-9f12bcc8b7c8)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7fe64fa9-e29f-4f98-88b1-1b7c21ddb0c5)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/46761307-b710-4748-b5b8-e3a68084c156)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/432189e7-92e0-4225-97b5-b919ad4d8ecb)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/eae18b65-a381-469d-87d1-3df7ef93cad7)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6473cb80-5f15-4471-9f95-07b4eb7068ac)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/70f7035e-8711-4f2f-940a-34661dda6bb9)

**Comment by wanyaland** [comment] 2020-10-01 11:56
@nirupamav . Needed clarity on this..Did the GH user remain of type lead ?

**Comment by nirupamav** [comment] 2020-10-05 05:54
Yes @wanyaland . It was still type Lead and was not updated as contact
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/22f4215b-3e4c-46a0-a5c6-5f15be8db436)

**Comment by wanyaland** [comment] 2020-10-05 14:03
@nirupamav could you kindly share the GH user account used ? or their corresponding LFusername

**Comment by nirupamav** [comment] 2020-10-05 14:11
@wanyaland 
I have only that test data to test this issue. Could you please create one for your github user and check

**Comment by dealako** [comment] 2021-01-04 20:59
Merged PR https://github.com/communitybridge/easycla/pull/2401 - ready for QA.

**Comment by amolsontakke3576** [comment] 2021-01-05 15:18
@vinod-kadam Verified and now email comes for the user who doesn't have LFID
![Screenshot from 2021-01-05 20-46-08.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/a4adf115-bebb-4e90-8ec5-9bd020a109eb)

**Closed** 2021-01-06 07:03 UTC
Labels: 01 - High, enhancement, tier-2, v2
