### ISSUE TITLE
V2 - Issues in company/{{companySFID}}/cla-managers endpoint

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1172] opened 2020-06-04 16:30 UTC
**Observed below issues in the endpoint to get CLA Managers From My Organization**
**User Story - #929, #936**
URL - {{apiserver}}/v4/company/{{companySFID}}/cla-managers
1. In response data for organization_name and organization_sfid is not returned
https://user-images.githubusercontent.com/60865903/83733779-a816cf00-a66b-11ea-9cdf-2ceab6563135.png
2. 403 is returned for user with lf-operations role and admin scope but with developer scope 200 is returned
3. API returns date when CLA was signed for Approved on and not the date when CLA Manager was added

**Comment by vinod-kadam** [comment] 2020-11-30 17:36
David to evaluate whether it is tier-1 or tier-2 or tier-3.

**Comment by dealako** [comment] 2020-11-30 23:47
@makkalot Marking this as a tier-3 ticket, but I'd like to have it resolved before EasyCLA v2 launch.

Regarding point 1 in the write-up, can you review the response data model and determine why the Company Name and SFID are not returned in the response?  It seems like the information would be available - not sure why it was excluded from the response payload.


Regarding point 2, I believe that this API is only used primarily within the Organization Dashboard (v2 corporate console) and by default anyone (everyone) with [the user's role](https://github.com/LF-Engineering/acs-cli/blob/master/services/11-cla-service.yaml#L856) can view it.  Can you confirm this by reviewing the `acs-cli` configuration for the [endpoint](https://github.com/LF-Engineering/acs-cli/blob/master/services/11-cla-service.yaml#L279)?

Point 3, yes, this is a known limitation as we currently only store times for certain events with the signature.  Obviously, the audit log will have all the details, but it currently is not stored with the signature record.  One potential workaround is to encode when cla managers are added/removed from the CLA into a separate column which includes a JSON structure, such as:

```
[
  {"event":"cla_manager_added", "user_lfid": "vinod-kadam", "name":"Vinod Smith", "email": "vinod@foo.com", "time": "2020-10-22T13:21:31.904482+0000"},
    {"event":"cla_manager_added", "user_lfid": "sameer-patel", "name":"Sameer Patel", "email": "sameer@foo.com", "time": "2020-10-23T12:22:32.904482+0000"},
  {"event":"cla_manager_removed", "user_lfid": "vinod-kadam", "name":"Vinod Smith", "email": "vinod@foo.com", "time": "2020-10-24T18:03:21.904482+0000"}
]
```

**Comment by thakurveerendras** [comment] 2020-12-18 14:35
Tested issue on staging environment with **lf-operations** role & found below Results

**Point 1** :  Worked as expected
**Point 2** :  I am not sure for what is expected Results here
**Point 3** : Worked as expected

Here is details results

**Point 1** :  Now Proper organization_name & organization_sfid appears on API response
"organization_name": "Proxima",
"organization_sfid": "0012M00002MnADGQA3",

API : https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/company/{{companySFID}}/project/{{projectSFID}}/cla-managers

**Point 3** :  As expected 7 limitation we are getting only **approved_on** record

API Response :`{
    "list": [
        {
            "added_on": "",
            "approved_on": "2020-12-17T13:51:32.501662+0000",
            "cla_group_name": "claVeerFoundation",
            "email": "veerendrat@proximabiz.com",
            "lf_username": "veerendrat",
            "name": "Veerendra Thakur",
            "organization_name": "Proxima",
            "organization_sfid": "0012M00002MnADGQA3",
            "project_id": "c6df3a6b-a200-4494-879b-d39e18dc9ce3",
            "project_name": "Veer Foundation-Test-001",
            "project_sfid": "a096s0000003knwAAA",
            "user_sfid": "0036s000005YX1DAAW"
        }
    ]
}`

**Point 3** : I am getting 404 Not Found response for API end point for **admin** &  **developer** scope under lf-operations role . Note that I am not sure for what is expected Results here

API Endpoint : https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/company/{{companySFID}}/cla-managers

Here is Point 3 API Response :`{
    "code": 404,
    "message": "path /v4/company/0012M00002MnADGQA3/cla-managers was not found"
}`

**Comment by vinod-kadam** [comment] 2020-12-18 16:32
@dealako  to review it.

**Comment by vinod-kadam** [comment] 2020-12-21 06:25
As discussed in the 18-Dec standup, lf-operations should be able to access the endpoint.

**Comment by vinod-kadam** [comment] 2020-12-21 08:13
As updated by @wanyaland , 404 is basically the error code returned for no cla managers found for the company.
@thakurveerendras, please add few cla managers and then again fire the endpoint for lf-operations user & then check.

**Comment by thakurveerendras** [comment] 2020-12-21 14:39
Hi @wanyaland 

**Point 3** is retested on staging environment & found 403 forbidden error for admin scope & 404 Not found for developer scope, 

companySFID : "0012M00002MnADGQA3",
API Endpoint : https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/company/{{companySFID}}/cla-managers

Here is step I follow on staging environment:

Case 1 : **developer** scope 

1. Added proxima company in cla-manager
2. Added **lf-operations** role with **developer** scope 
3. Run API endpoint

Results obtains : 404 not found
Expected : 200 OK Response

Case 2:  **Admin** scope

1. Removed lf-operations role with developer scope
2. Added  **lf-operations** role with **Admin** scope
3. Run API endpoint

Results obtains : 403 forbidden
Expected : 200 OK Response

**Comment by dealako** [comment] 2020-12-21 22:35
Created PR - read for DEV review.

Permissions Matrix Source: https://docs.google.com/spreadsheets/d/1KffX1dmJEEMhXQYXDpe7RTsuFTkuEMgjYLak07b4nI4/edit?pli=1#gid=756183687

**Comment by dealako** [comment] 2020-12-22 20:27
@thakurveerendras 

ready for review.

**Comment by thakurveerendras** [comment] 2020-12-23 11:56
Hi @dealako ,

Still, I am getting same results  for API Endpoint on **staging** environment i.e. **404 not found** for **developer** scope & **403 forbidden** for **Admin** scope

API Endpoint : https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/company/{{companySFID}}/cla-managers
companySFID : "0012M00002MnADGQA3",

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/448d6546-8f69-49b8-a095-c6c8f924c41c)

**Comment by wanyaland** [comment] 2020-12-23 14:48
@thakurveerendras . This endpoint actually does not exist in the cla-service which explains the 404 and 403. The 403 is due to the acs configuration not having the endpoint and the 404 is due to cla-service not recognising it.
cc @dealako

**Comment by vinod-kadam** [comment] 2020-12-23 16:07
As discussed in the standup, @wanyaland  will provide the correct endpoint to get cla managers based on cla-group-id.

**Comment by vinod-kadam** [comment] 2020-12-24 11:42
@thakurveerendras, please check the following endpoint.
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectClaManagers

**Comment by thakurveerendras** [comment] 2020-12-24 12:46
Hi @vinod-kadam ,

Issue is tested on staging with above mentioned end point & found below results,

1. Added proxima company in **cla-manager** : 200 OK status 
2. **lf-operations** role with **developer** scope : 200 OK status 
3. **lf-operations** role with **admin** scope : **403 Forbidden** status 

**API Endpoint :**
```
"organization_name": "Proxima",
"organization_sfid": "0012M00002MnADGQA3",

API : https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/company/{{companySFID}}/project/{{projectSFID}}/cla-managers
```

Developer scope :
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/7f690821-773c-4282-abb0-702e856f7c24)

Admin Scope: 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/8a1c046c-c35c-4bbe-a1c2-86ee7be4a0d2)

cla-manager: 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/747826f0-da4b-4e8d-9497-0d7061e6e9f6)

**Comment by vinod-kadam** [comment] 2020-12-24 13:40
As discussed between @wanyaland , @thakurveerendras  & @vinod-kadam , it makes sense to not allow the cla managers endpoint even for developer scope as we understand that for admin scope it was not allowed by design.
@pranab-bajpai please provide clarification whether LF-operations Admin & Developer scope should be able to access the cla mangers end-point? Please provide the reason as well.

**Comment by vinod-kadam** [comment] 2020-12-28 16:46
@dealako to look at it.

**Comment by vinod-kadam** [comment] 2020-12-29 17:27
As discussed with @dealako  & @pranab-bajpai  set Release to Post-EasyCLAv2Release as it is not a blocker in anyway for 1st release. We will work it out later.

**Comment by dealako** [comment] 2022-08-22 15:44
We are closing this old issue.  We can re-evaluate at a later date if needed.

**Closed by dealako** 2022-08-22 15:44 UTC
Labels: bug, v2, API, tier-3
