### ISSUE TITLE
Contributor Console Individual CLA flow when company is not found. Step 3

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1018] opened 2020-04-28 18:15 UTC
Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/app-easycla#/page/Dab111f6a971bc1cd42c819a1770bc817)for the contributor console of EasyCLA.

![image](https://user-images.githubusercontent.com/57362064/80522497-49ff1980-8952-11ea-96c6-c6697f592856.png)

Step 3 in Table 4 in the PRD below
https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2

##Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1, Sev 2 bug(s)

**Comment by amolsontakke3576** [comment] 2020-08-19 07:44
@dealako This flow is also integrated successfully.

**Comment by nirupamav** [comment] 2020-08-19 08:53
@amolsontakke3576 
I am not able to add Company due to below error and blocked with Company Not Found flow
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/86e098ad-7adf-4238-92aa-14eb9b0cf61c)

**Comment by amolsontakke3576** [comment] 2020-08-19 09:32
@wanyaland Can you please look at this issue?

**Comment by amolsontakke3576** [comment] 2020-08-19 10:09
@dealako @pranab-bajpai @wanyaland As per the latest discussion LF login now deprecated from Add Organization flow so `user_email` required to create organization may be `github_user_email`. So we need to handle this use case when the user has no LFID and he has it's GitHub email. (I have handled user case when GitHub user has private email).

**Comment by nirupamav** [comment] 2020-08-25 06:52
**Still facing same issue**
Tried below values
http://www.Augnewcompanynirupamav.com
Augnewcompanynirupamav

https://www.Augnewcompanynirupamav.com
Augnewcompanynirupamav

https://Augnewcompanynirupamav.com
Augnewcompanynirupamav

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7808ab1d-3198-42ab-bcc0-a01f018ce77e)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bdced03a-91c3-4dd6-8121-a2fc4a3ab458)

**Comment by dealako** [comment] 2020-08-25 18:43
Reviewing - will add until tests and update the regex. Will create a new fix/PR for this. For UI display, just say it must be a valid website URL.

**Comment by amolsontakke3576** [comment] 2020-08-25 18:51
@dealako I have changed website regex in my current task same as mentioned in above screenshot. So frontend change will reflect in next PR

**Comment by dealako** [comment] 2020-08-25 22:34
Merged PR - deploying to DEV.

**Comment by nirupamav** [comment] 2020-08-26 06:43
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e85d32d2-0b01-4243-bec9-71cc0d935fe0)

**Closed** 2020-08-29 00:49 UTC
Labels: 02 - Med High, Console - Contrib, enhancement, v2
