### ISSUE TITLE
Gerrit: ICLAs & CCLAs Process stop at "You are being redirected to the login page." 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4240] opened 2024-02-09 10:17 UTC
## Summary

Gerrit: ICLAs & CCLAs Process stop at the "You are being redirected to the login page." 

## Background

Steps:
1. Go to "https://gerrit.linuxfoundation.org/infra/settings/new-agreement" page
2. Select the Gerrit project
3. Click on "[Please review the agreement.](https://api.staging.lfcla.com/v2/gerrit/4405798d-913c-4a8d-a906-dd61d91c2d62/individual/agreementUrl.html)" link
4. See-"You are being redirected to the login page." open & keep loading

## Expected behavior

User should redirect to docusigned page

## Screenshots

![image](https://github.com/communitybridge/easycla/assets/75417507/39516fc3-8fc7-4a01-8269-b482aeefc793)

**Comment by nickmango** [comment] 2024-02-10 18:50
@thakurveerendras kindly check. As you had identified earlier there was an auth issue . You can check the docusign gerrit flow

**Comment by thakurveerendras** [comment] 2024-02-12 04:52
Tested issue on dev site and found that it is reproducible when we login with different user (lf user which having different Gerrit email address)

**Comment by nickmango** [comment] 2024-02-12 17:45
@thakurveerendras As confirmed with the production project JuanSebastian availed for testing... this is as well reproducible in prod and is not a regression issue 
cc @mlehotskylf

**Comment by mlehotskylf** [comment] 2024-02-21 16:45
@amolsontakke3576 thank you for looking into this, please let us know what is the latest for this ticket. Thanks!

**Comment by mlehotskylf** [comment] 2024-02-23 16:43
This is related to #3946 (it has the same root cause).

**Comment by mlehotskylf** [comment] 2024-03-04 16:47
This is fixed in DEV as reported. Moving to QA.

**Comment by jarias-lfx** [comment] 2024-03-04 17:39
Confirmed the re-direction is working in Production for ICLA and CCLA. However, when the users perform an ICLA signature or proceed with ECLA for CCLA, the contributors should be added to the respective project LDAP group. This is currently not happening. Without this, even after signing, the users are unable to contribute, which is still a blocker.

**Comment by nickmango** [comment] 2024-03-06 11:55
@jarias-lfx resolved the ldap group addition however changes have been deployed in dev 
cc @mlehotskylf

**Comment by mlehotskylf** [comment] 2024-03-07 16:42
We discovered that user was not added to LDAP. This is fixed and ready to deploy to PROD.

**Comment by mlehotskylf** [comment] 2024-04-25 22:09
This is fixed and deployed to PROD so closing this ticket.

**Closed by mlehotskylf** 2024-04-25 22:09 UTC
Labels: bug, 01 - High, Gerrit
